import type { Locale } from './site';

export type PageContent = {
  eyebrow: string;
  title: string;
  description: string;
  intro: string;
  sections: { title: string; body: string }[];
  bullets: string[];
  cta: string;
};

export const pages: Record<string, Record<Locale, PageContent>> = {
  marketplace: {
    ar: {
      eyebrow: 'سوق الباك لينك',
      title: 'الموقع المناسب. للرابط المناسب.',
      description: 'اكتشف سوق Linkaza لشراء الباك لينك والجيست بوست. قارن مواقع النشر حسب التخصص والجمهور والسعر واللغة وشروط العرض، ثم اختر ما يناسب حملتك.',
      intro: 'قرار نشر أفضل يبدأ بسؤال واضح: أين يقرأ عملاؤك، وما المقال الذي يستحق النشر هناك؟ في Linkaza تقارن الموقع والعرض قبل أن تدفع.',
      sections: [
        { title: 'ابدأ من جمهورك', body: 'حدّد لغة حملتك والسوق الذي تستهدفه، ثم ابحث عن مواقع ترتبط بموضوعك. الموقع المتخصص الذي يقرأه عميلك المحتمل قد يكون أنسب من موقع عام بمؤشر أعلى، خصوصاً عندما يكون المقال جزءاً طبيعياً من اهتمام القارئ.' },
        { title: 'اقرأ ما وراء المؤشرات', body: 'راجع اتجاه الزيارات وأمثلة المقالات والصفحات التي تجذب الجمهور. استخدم مؤشرات قوة النطاق مثل DA أو DR أو AS للمقارنة، مع الانتباه إلى مصدر كل رقم وتاريخ تحديثه وطريقة تقديره.' },
        { title: 'قارن السعر بما يشمله', body: 'لا يكفي أن تعرف سعر النشر. اسأل هل يشمل كتابة المقال؟ هل توجد متطلبات صور أو مراجعة؟ هل يسمح الناشر بروابط داخلية أو روابط موثوقة؟ مقارنة التكلفة الحقيقية تمنع قرارات شراء عشوائية.' },
        { title: 'افهم العرض قبل الطلب', body: 'تحقّق من نوع الرابط ومدة بقاء المقال وشروط الناشر وما يحدث إذا احتاج الطلب إلى تعديل. تجد العروض المتاحة وتفاصيل تنفيذها داخل حسابك، لتبني قرارك على شروط واضحة لا على تخمين.' },
        { title: 'اختر رابطاً يخدم الصفحة المستهدفة', body: 'الرابط الجيد يكمل الفقرة التي يظهر فيها. اربط بصفحة جاهزة لاستقبال القارئ، مثل دليل متخصص أو خدمة واضحة أو صفحة منتج مرتبطة بموضوع المقال.' },
      ],
      bullets: ['تخصص يرتبط بمحتواك', 'جمهور يناسب سوقك', 'سعر وشروط واضحة قبل الطلب', 'صفحة مستهدفة مناسبة للرابط'],
      cta: 'استكشف السوق',
    },
    en: {
      eyebrow: 'The backlink marketplace',
      title: 'The right website. The right connection.',
      description: 'Explore the Linkaza backlink and guest post marketplace. Compare publisher relevance, audiences, pricing, languages and placement terms before choosing your next opportunity.',
      intro: 'A better placement starts with a clear question: where does your customer read, and what article belongs there? Linkaza helps you compare the website and offer before you pay.',
      sections: [
        { title: 'Start with your audience', body: 'Choose your target language and market, then look for publishers that cover your subject. A focused publication your customers actually read can be a better fit than a general website with a higher score, especially when the article naturally serves the reader.' },
        { title: 'Look beyond the headline metric', body: 'Review traffic trends, recent articles and the pages attracting readers. Use DA, DR or authority-style metrics as comparison signals, and check the source, freshness and limits of the available data.' },
        { title: 'Compare the full cost', body: 'The listed placement price is only part of the decision. Confirm whether writing is included, whether images or revisions are required, and whether the publisher expects supporting authority links or internal links.' },
        { title: 'Know what you are ordering', body: 'Check the link attributes, article retention period, editorial requirements and what happens if an order needs correction. Current opportunities and order details are available in your account so your decision is based on terms, not assumptions.' },
        { title: 'Choose a useful destination page', body: 'A useful backlink should continue the reader’s task. Point to a page that is ready: a specialist guide, a clear service page, original research or a product category connected to the article.' },
      ],
      bullets: ['Relevant subject coverage', 'An audience that fits', 'Pricing and terms you can review', 'A destination page that fits the link'],
      cta: 'Explore the marketplace',
    },
  },
  pricing: {
    ar: {
      eyebrow: 'التكلفة والميزانية',
      title: 'اعرف تكلفة الطلب قبل أن تبدأ.',
      description: 'تعرّف على طريقة تسعير الباك لينك والجيست بوست في Linkaza: الدفع حسب الطلب، وأسعار الناشرين، وتكلفة المحتوى وشروط النشر.',
      intro: 'تختلف تكلفة الباك لينك حسب الموقع واللغة والمحتوى وشروط النشر. لا تعتمد على سعر عام؛ راجع ما يشمله كل عرض قبل أن تقرر.',
      sections: [
        { title: 'الدفع حسب الطلب', body: 'تعمل Linkaza بنظام الدفع بحسب الاستخدام. يحدّد الناشر سعر عرضه، ويمكنك مراجعة السعر داخل السوق قبل الشراء، مع الدفع لكل طلب أو من رصيد الحساب بحسب الخيارات المتاحة داخل المنصة.' },
        { title: 'قارن التكلفة الكاملة', body: 'تحقّق مما يشمله العرض: النشر فقط أم كتابة المقال أيضاً، ومتطلبات الصور أو المراجعة أو الإضافات. قارن عروضاً متقاربة في الجمهور والتخصص حتى يكون فرق السعر مفهوماً، ولا تقارن موقعاً عاماً بموقع متخصص كأنهما فرصة واحدة.' },
        { title: 'احسب تكلفة المحتوى', body: 'إذا كان المقال غير جاهز، أدخل تكلفة الكتابة والتحرير ضمن الميزانية. الموقع الجيد لا ينقذ مقالاً ضعيفاً، لذلك لا تفصل تكلفة المحتوى عن قرار الشراء.' },
        { title: 'ابدأ بحملة قابلة للمراجعة', body: 'بدلاً من شراء عدد كبير من الروابط دفعة واحدة، ابدأ بمجموعة تستطيع مراجعة موجزها وتسليمها ونتائجها. بعد ذلك عدّل المعايير: اللغة، التخصص، السعر، ونوع الصفحات التي تستحق روابط إضافية.' },
        { title: 'شروط النشر جزء من القيمة', body: 'راجع مدة بقاء المقال والرابط وأي ضمان محدد في العرض. تُدرس طلبات الاسترداد وفق حالة الطلب والشروط المتفق عليها؛ لا توجد مدة ضمان موحّدة تُفترض لكل المواقع.' },
      ],
      bullets: ['سعر الناشر قبل الشراء', 'ميزانية تختارها لكل حملة', 'تكلفة المحتوى ضمن القرار', 'تفاصيل العرض هي مرجعك'],
      cta: 'شاهد العروض المتاحة',
    },
    en: {
      eyebrow: 'Pricing & budgets',
      title: 'Know the order cost before you start.',
      description: 'Understand Linkaza backlink and guest post pricing: pay per order, compare publisher offers, and check content costs and placement terms before buying.',
      intro: 'Backlink pricing changes with the website, language, content and placement terms. Do not rely on a generic price; review what each offer includes before you decide.',
      sections: [
        { title: 'Pay as you go', body: 'Linkaza operates on a pay-as-you-go basis. Publishers set their placement prices, which you can review in the marketplace before purchase. Available payment options include individual orders or your account balance inside the platform.' },
        { title: 'Compare the complete cost', body: 'Check whether an offer covers publication alone or includes writing, and confirm any image, revision or additional-content requirements. Compare publishers with similar audiences and subject coverage rather than treating all listings as equal.' },
        { title: 'Budget for content quality', body: 'If the article is not ready, include writing and editing in the plan. A good website cannot rescue a weak article, so content production belongs in the budget from the start.' },
        { title: 'Start at a reviewable scale', body: 'Instead of buying many placements at once, begin with a group you can brief, inspect and learn from. Then refine the criteria: language, topic, price level and destination pages that deserve more attention.' },
        { title: 'Read the placement terms', body: 'Check how long the article and link must remain live and any guarantee included in the listing. Refund requests are assessed against the order and its agreed terms; do not assume one guarantee period applies to every publisher.' },
      ],
      bullets: ['Publisher prices before purchase', 'A budget for each campaign', 'Content costs included in the decision', 'Offer-specific publication terms'],
      cta: 'View available offers',
    },
  },
  solutions: {
    ar: {
      eyebrow: 'حلول Linkaza',
      title: 'طريقة عملك. نقطة البداية.',
      description: 'حلول بناء الروابط للوكالات ومستشاري السيو والشركات والناشرين. اختر المسار المناسب لحملات الباك لينك والجيست بوست مع Linkaza.',
      intro: 'تختلف الحملات، ويبقى القرار الجيد مبنياً على جمهور مناسب ومحتوى مفيد وتفاصيل واضحة.',
      sections: [
        { title: 'للوكالات والمستشارين', body: 'ابدأ بمعايير اختيار ثابتة لكل عميل: القطاع، اللغة، الجمهور والميزانية. استخدمها لبناء قائمة نشر يسهل شرحها ومراجعتها، مع توثيق سبب اختيار كل موقع.' },
        { title: 'للشركات والمتاجر', body: 'اربط كل فرصة بصفحة ذات قيمة: دليل متخصص، دراسة أصلية، فئة منتجات أو خدمة واضحة. فكّر فيما سيجده الزائر بعد النقر، وكيف ستقيس اهتمامه بعلامتك.' },
        { title: 'للناشرين', body: 'حوّل خبرتك التحريرية وجمهورك إلى عرض واضح للمعلنين. اشرح تخصص موقعك وشروط قبول المحتوى والسعر والمدة المتوقعة، مع الحفاظ على تجربة قرّائك.' },
        { title: 'خطة واحدة لا تناسب الجميع', body: 'حملة وكالة تحتاج موافقات وتقارير، وحملة شركة تحتاج صفحات جاهزة وقياساً واضحاً، والناشر يحتاج شروطاً تحمي جمهوره. لذلك تبدأ حلول Linkaza من طريقة العمل، لا من عدد الروابط فقط.' },
        { title: 'القرار يبدأ من التفاصيل', body: 'قبل طلب باك لينك أو جيست بوست، راجع اللغة والتخصص والسعر ومتطلبات المحتوى ومدة التنفيذ. هذه التفاصيل تساعدك على اختيار فرصة تناسب الهدف بدلاً من شراء نشر لا يخدم الخطة.' },
      ],
      bullets: ['الوكالات ومستشارو السيو', 'الشركات والمتاجر الإلكترونية', 'المواقع والناشرون', 'تفاصيل واضحة قبل الطلب'],
      cta: 'اعثر على فرصتك التالية',
    },
    en: {
      eyebrow: 'Built around your work',
      title: 'Different teams. Better connections.',
      description: 'Explore Linkaza link building solutions for agencies, SEO consultants, businesses and publishers, with relevant audiences and clear placement decisions.',
      intro: 'Your workflow may differ. The essentials stay the same: a relevant audience, useful content and an offer you understand.',
      sections: [
        { title: 'For agencies and consultants', body: 'Set selection criteria for every client: industry, language, audience and budget. Use them to build a publisher shortlist you can explain, review and connect to the campaign brief.' },
        { title: 'For businesses and stores', body: 'Give every placement a useful destination: an expert guide, original research, a product category or a clear service page. Consider the experience after the click and how you will measure interest.' },
        { title: 'For publishers', body: 'Turn your editorial expertise and audience into a clear offer. Describe your subject coverage, content requirements, price and expected timeline while protecting the experience your readers value.' },
        { title: 'One workflow does not fit everyone', body: 'An agency campaign needs approvals and reporting. A business campaign needs ready destination pages and clear measurement. A publisher needs terms that protect its audience. Linkaza solutions start with the workflow, not only a link count.' },
        { title: 'Details come before decisions', body: 'Before ordering a backlink or guest post, review language, topic fit, price, content requirements and delivery expectations. These details help you choose an opportunity that serves the plan rather than buying publication for its own sake.' },
      ],
      bullets: ['Agencies and SEO consultants', 'Businesses and ecommerce teams', 'Independent publishers', 'Clear details before ordering'],
      cta: 'Find your next opportunity',
    },
  },
  agencies: {
    ar: {
      eyebrow: 'للوكالات',
      title: 'حملات يمكن أن تقف وراءها.',
      description: 'خطّط لحملات باك لينك وجيست بوست لعملاء وكالتك مع Linkaza. قارن الناشرين، اضبط متطلبات المحتوى، ووثّق قرارات النشر.',
      intro: 'كل عميل له سياقه. اجمع اختيارات النشر حول خطة واضحة يمكن لفريقك تنفيذها ولعميلك فهمها.',
      sections: [
        { title: 'معايير خاصة بكل عميل', body: 'أنشئ موجزاً يحدد السوق واللغة والصفحات المستهدفة والناشرين المستبعدين. اجعل الصلة بالموضوع معياراً أساسياً، ثم قارن البيانات والتكلفة وشروط النشر.' },
        { title: 'موافقة تستند إلى تفاصيل', body: 'شارك سبب ترشيح الموقع وزاوية المقال والميزانية مع العميل قبل التنفيذ. وثّق النص الرابط ومتطلبات العلامة، حتى يعرف الكاتب والناشر ما الذي تم اعتماده.' },
        { title: 'تنظيم يقلل أخطاء التسليم', body: 'اجمع في كل طلب الصفحة المستهدفة، النص الرابط، زاوية المقال، متطلبات العميل، وما لا يجب ذكره. كلما كان الموجز محدداً قلّت المراجعات غير الضرورية بعد التسليم.' },
        { title: 'فرّق بين عمل الوكالة ونتائج البحث', body: 'التقرير الجيد يثبت ما نُفذ: أين نُشر المقال، ما الرابط، وما شروط الطلب. أما تغيّر الترتيب أو الزيارات فيحتاج سياقاً أوسع يشمل تحديثات الموقع والموسم والمنافسين.' },
        { title: 'تقرير يشرح العمل', body: 'اجمع روابط المقالات المنشورة وتواريخها وصفحاتها المستهدفة. افصل بين تنفيذ الطلب ومؤشرات الأداء، وقدّم سياقاً لتغيّر الزيارات أو التحويلات بدلاً من نسبته تلقائياً إلى رابط واحد.' },
      ],
      bullets: ['اختيارات مرتبطة بموجز العميل', 'محتوى ومتطلبات موثّقة', 'تنفيذ قابل للمراجعة', 'تقارير مفهومة لأصحاب القرار'],
      cta: 'خطّط لحملة عميلك',
    },
    en: {
      eyebrow: 'For agencies',
      title: 'Campaigns you can stand behind.',
      description: 'Plan backlink and guest post campaigns for agency clients with Linkaza. Compare publishers, define content requirements and document placement decisions.',
      intro: 'Each client brings a different context. Build a publishing plan your team can execute and your client can understand.',
      sections: [
        { title: 'Criteria for every account', body: 'Define the target market, language, destination pages and excluded publishers. Make topical relevance a first requirement, then compare available data, cost and publication terms.' },
        { title: 'Approvals with context', body: 'Share your publisher rationale, proposed article angle and budget before ordering. Record approved anchor text and brand requirements so the writer and publisher work from the same brief.' },
        { title: 'Organization reduces delivery issues', body: 'Keep the destination page, anchor text, article angle, client requirements and exclusions in each order. The more precise the brief, the fewer avoidable revisions after delivery.' },
        { title: 'Separate agency work from search outcomes', body: 'A good report proves what was delivered: where the article was published, which link was used and what terms applied. Ranking or traffic changes need wider context, including website updates, seasonality and competitors.' },
        { title: 'Reporting that explains the work', body: 'Keep the published URLs, dates and destination pages together. Separate delivery from performance, and give traffic or conversion changes their proper context instead of attributing them to one link.' },
      ],
      bullets: ['Client-specific publisher criteria', 'Documented content requirements', 'Reviewable delivery', 'Clear stakeholder reporting'],
      cta: 'Plan your next client campaign',
    },
  },
  consultants: {
    ar: {
      eyebrow: 'لمستشاري السيو',
      title: 'خبرتك في الاختيار تصنع الفرق.',
      description: 'استخدم Linkaza لاختيار فرص باك لينك وجيست بوست تناسب عملاءك. إرشادات للمقارنة والتخطيط ومراجعة النشر لمستشاري تحسين محركات البحث.',
      intro: 'وفّر تركيزك لما يحتاج إلى خبرتك: فهم السوق، وتقييم الموقع، واختيار موضوع يمكن نشره بثقة.',
      sections: [
        { title: 'قائمة أقصر وأكثر صلة', body: 'حدّد أسباب الاستبعاد مبكراً: لغة لا تناسب الحملة، محتوى بعيد عن المجال، أو بيانات يصعب تفسيرها. ركّز وقت التقييم على المواقع التي تحقق المعايير الأساسية.' },
        { title: 'التوصية تبدأ من التحليل', body: 'راجع الصفحة المستهدفة قبل البحث عن روابط لها. إذا كانت لا تجيب عن حاجة الزائر أو يصعب استخدامها، فقد يكون تحسينها هو الخطوة الأجدى قبل الاستثمار في النشر.' },
        { title: 'استخدم المنافسين كدليل لا كنسخة', body: 'راقب أين يظهر المنافسون، لكن لا تنسخ كل رابط أو ناشر. اسأل لماذا كان الموقع مناسباً لهم، وهل يخدم جمهور عميلك وصفحته المستهدفة بالدرجة نفسها.' },
        { title: 'وثّق سبب الرفض أيضاً', body: 'قائمة المواقع المستبعدة مفيدة مثل قائمة المرشحين. سجّل سبب الاستبعاد: لغة غير مناسبة، محتوى ضعيف، تجربة قراءة مزعجة، أو شروط نشر لا تناسب العميل.' },
        { title: 'مراجعة منظمة بعد النشر', body: 'قارن المقال المنشور بالموجز، وافحص الرابط ووجهته وخصائصه. احتفظ بتاريخ التنفيذ وملاحظاتك لتبني عليها قرارات الحملة التالية.' },
      ],
      bullets: ['معايير تقييم قابلة للتكرار', 'قرارات تخدم خطة السيو', 'أسباب قبول ورفض واضحة', 'تفاصيل يسهل الرجوع إليها'],
      cta: 'ابدأ قائمة النشر الخاصة بك',
    },
    en: {
      eyebrow: 'For SEO consultants',
      title: 'Your judgment makes the difference.',
      description: 'Use Linkaza to find backlink and guest post opportunities for your clients, with a practical approach to publisher selection, content briefs and delivery reviews.',
      intro: 'Keep your attention on the work that needs your expertise: understanding the market, assessing a publisher and choosing an article topic you can defend.',
      sections: [
        { title: 'A tighter, more relevant shortlist', body: 'Define exclusions early: the wrong language, unrelated subject coverage or data that needs more explanation. Spend your review time on publishers that meet the basic campaign requirements.' },
        { title: 'Advice starts with analysis', body: 'Review the destination page before finding links to it. If it does not answer a visitor’s need or is difficult to use, improving that page may be the better first investment.' },
        { title: 'Use competitors as evidence, not a copybook', body: 'Review where competitors appear, but do not copy every link or publisher. Ask why a website worked for them and whether it serves your client’s audience and destination page in the same way.' },
        { title: 'Document rejections too', body: 'A rejected-publisher list can be as useful as a shortlist. Record the reason: wrong language, weak content, poor reading experience or publication terms that do not fit the client.' },
        { title: 'A repeatable delivery review', body: 'Compare the live article with the brief, then check the link, destination and attributes. Keep the delivery date and your observations so the next campaign benefits from what you learned.' },
      ],
      bullets: ['Repeatable publisher evaluation', 'Decisions connected to SEO strategy', 'Clear accept and reject reasons', 'A clear record of each placement'],
      cta: 'Build your publisher shortlist',
    },
  },
  businesses: {
    ar: {
      eyebrow: 'للشركات والمتاجر',
      title: 'دع علامتك تدخل الحديث المناسب.',
      description: 'اكتشف فرص نشر وباك لينك للشركات والمتاجر مع Linkaza. اختر جمهوراً يناسب نشاطك ومحتوى يشرح قيمتك وصفحات تستقبل الزيارات بوضوح.',
      intro: 'اختر مساحات يتابعها جمهورك، وقدّم محتوى يساعده على فهم ما تعرفه وما تقدّمه.',
      sections: [
        { title: 'انطلق من سؤال العميل', body: 'ما الذي يسأل عنه جمهورك قبل الشراء؟ اجعل المقال يجيب عن سؤال حقيقي بمثال أو مقارنة أو خبرة عملية، ثم اربط بمصدر مفيد داخل موقعك.' },
        { title: 'اختر وجهة جاهزة للزائر', body: 'تأكد أن صفحة الوصول سريعة وواضحة وتعمل على الهاتف. وجّه القارئ إلى الصفحة الأكثر ارتباطاً بسياق المقال، بدلاً من إرسال جميع الروابط إلى الصفحة الرئيسية.' },
        { title: 'استخدم الباك لينك ضمن رحلة الشراء', body: 'لا تجعل كل رابط هدفه البيع المباشر. بعض الروابط تخدم الوعي، مثل دليل يشرح المشكلة، وبعضها يخدم المقارنة، مثل صفحة خدمة أو فئة منتجات. اربط كل فرصة بالمرحلة التي يناسبها المحتوى.' },
        { title: 'وازن بين العربي والإنجليزي', body: 'إذا كنت تستهدف أكثر من سوق، افصل الرسائل حسب اللغة والبلد. الجمهور العربي يحتاج أمثلة وسياقاً مختلفاً عن جمهور إنجليزي، والصفحة المستهدفة يجب أن تطابق لغة المقال قدر الإمكان.' },
        { title: 'قِس ما يهم النشاط', body: 'تابع زيارات الإحالة والتفاعل والاستفسارات المرتبطة بها عندما تكون أدوات القياس متاحة. اقرأ أداء البحث ضمن الخطة التسويقية كاملة، مع مراعاة الموسم والتغييرات الأخرى في موقعك.' },
      ],
      bullets: ['وصول إلى جمهور ذي صلة', 'محتوى يشرح خبرتك', 'صفحات جاهزة لاستقبال الزائر', 'أهداف مرتبطة بنشاطك'],
      cta: 'اكتشف فرص علامتك',
    },
    en: {
      eyebrow: 'For businesses',
      title: 'Put your brand in the right conversation.',
      description: 'Discover publishing and backlink opportunities for businesses with Linkaza. Connect relevant audiences with useful content and a clear destination on your website.',
      intro: 'Choose publications your audience cares about, then give their readers a useful reason to discover your brand.',
      sections: [
        { title: 'Start with a customer question', body: 'What does your audience need to understand before buying? Answer a real question with a practical example, comparison or experience, and point to a genuinely useful resource on your website.' },
        { title: 'Make the destination ready', body: 'Check that your landing page is fast, clear and usable on mobile. Link to the page that best continues the article’s subject instead of sending every visitor to the homepage.' },
        { title: 'Use backlinks across the buying journey', body: 'Not every link should push a direct sale. Some placements support awareness with an educational guide. Others support comparison with a service page or product category. Match each opportunity to the article’s purpose.' },
        { title: 'Separate Arabic and English intent', body: 'If you target more than one market, write for each language and country separately. Arabic readers need their own examples and context, and the destination page should match the article language whenever possible.' },
        { title: 'Measure what matters to the business', body: 'Where your analytics allow it, review referral visits, engagement and enquiries. Interpret search performance in the context of your wider marketing work, seasonality and other website changes.' },
      ],
      bullets: ['A relevant readership', 'Content that demonstrates expertise', 'Destination pages ready for visitors', 'Goals connected to your business'],
      cta: 'Find opportunities for your brand',
    },
  },
  publishers: {
    ar: {
      eyebrow: 'للناشرين',
      title: 'جمهورك قيمة. قدّمها بوضوح.',
      description: 'انضم إلى Linkaza كناشر واعرض فرص النشر على موقعك. وضّح تخصصك وشروط المقالات والأسعار ومتطلبات المحتوى للمعلنين المناسبين.',
      intro: 'افتح باب التعاون مع علامات ترتبط باهتمامات قرّائك، مع شروط نشر تحافظ على هويتك التحريرية.',
      sections: [
        { title: 'عرّف بموقعك بدقة', body: 'اذكر لغة الموقع وتخصصه والجمهور الذي يخدمه. قدّم بيانات يمكنك إثباتها وأمثلة حديثة من محتواك، وميّز بوضوح بين الأرقام المقاسة والتقديرات الخارجية.' },
        { title: 'ضع شروطك قبل استقبال الطلبات', body: 'حدّد الموضوعات المقبولة ومتطلبات المقال والروابط والسعر ومدة التنفيذ المتوقعة. اشرح مدة بقاء النشر وأي شروط للمراجعة، حتى يبدأ التعاون بتوقعات متفقة.' },
        { title: 'حوّل العرض إلى قرار سهل', body: 'المعلن يحتاج أن يعرف هل موقعك مناسب قبل أن يطلب. اكتب التخصصات المقبولة، الدول أو الجمهور الأقوى، أمثلة للمواضيع الجيدة، وما لا تقبله بوضوح.' },
        { title: 'اجعل السعر قابلاً للفهم', body: 'اشرح ما يشمله السعر: النشر فقط، مراجعة المقال، كتابة المحتوى، الصور أو تعديلات محددة. السعر الواضح يقلل الأسئلة المتكررة ويرفع جودة الطلبات التي تصلك.' },
        { title: 'تابع الطلبات بمعايير تحريرية ثابتة', body: 'عند وصول طلب جديد، قارنه بشروطك قبل الموافقة: هل الموضوع مناسب؟ هل الرابط طبيعي؟ هل المقال يضيف شيئاً للقارئ؟ رفض الطلب غير المناسب يحافظ على ثقة جمهورك وقيمة موقعك.' },
        { title: 'حافظ على تجربة القارئ', body: 'راجع المحتوى لتتأكد من أصالته وصلته بالموقع. وضّح طبيعة التعاون المدفوع واستخدم خصائص الرابط المناسبة؛ القرار التحريري النهائي بالنشر يعود إليك.' },
      ],
      bullets: ['تخصص وجمهور واضحان', 'شروط نشر تحددها مسبقاً', 'سعر مفهوم قبل الطلب', 'مراجعة تحريرية قبل القبول', 'محتوى يناسب قرّاءك'],
      cta: 'انضم كناشر',
    },
    en: {
      eyebrow: 'For publishers',
      title: 'Your audience has value. Make it clear.',
      description: 'Join Linkaza as a publisher and present your website’s placement opportunities, editorial requirements and pricing to relevant advertisers.',
      intro: 'Work with brands that fit your readership while keeping the editorial standards that make your publication yours.',
      sections: [
        { title: 'Represent your publication accurately', body: 'Describe your language, subject coverage and audience. Provide evidence for the data you share and recent examples of your content. Distinguish measured figures from third-party estimates.' },
        { title: 'Set expectations before an order', body: 'Specify accepted subjects, article and link requirements, price and expected delivery time. Explain publication duration and revision terms so both sides understand the offer.' },
        { title: 'Make the offer easy to evaluate', body: 'Advertisers need to know whether your website is a fit before ordering. State accepted niches, strongest countries or audiences, good article examples and topics you do not accept.' },
        { title: 'Explain what the price includes', body: 'Make clear whether the price covers publication only, editorial review, writing, images or a defined number of changes. Clear pricing reduces repeated questions and improves order quality.' },
        { title: 'Review orders with consistent editorial rules', body: 'When a new order arrives, compare it with your terms before approval: is the topic relevant, is the link natural, and does the article add value for readers? Rejecting poor-fit orders protects your audience and your website.' },
        { title: 'Protect the reader experience', body: 'Review content for originality and relevance. Disclose paid relationships and use appropriate link attributes. As the publisher, you retain the final editorial decision about publication.' },
      ],
      bullets: ['A clearly described audience', 'Your publication requirements', 'Pricing that is easy to understand', 'Editorial review before approval', 'Content that belongs on your website'],
      cta: 'Join as a publisher',
    },
  },
  'content-service': {
    ar: {
      eyebrow: 'كتابة المحتوى',
      title: 'مقال يستحق القراءة. قبل الرابط.',
      description: 'خطّط لمحتوى عربي وإنكليزي مناسب للجيست بوست وبناء الروابط. تعرّف على موجز المقال ومعايير التحرير ومتطلبات خدمة المحتوى في Linkaza.',
      intro: 'الرابط لا يعوض مقالاً ضعيفاً. ابدأ بسؤال القارئ، ثم اجعل الرابط جزءاً طبيعياً من الإجابة.',
      sections: [
        { title: 'موجز واضح يصنع مقالاً أفضل', body: 'حدّد القارئ المستهدف، والسؤال الذي يجيب عنه المقال، وزاويته، ومصادره. أضف الصفحة المستهدفة ومتطلبات الناشر ونبرة علامتك قبل الاتفاق على الكتابة.' },
        { title: 'لغة تناسب الجمهور', body: 'المحتوى العربي يحتاج صياغة أصلية وسياقاً محلياً، والنسخة الإنكليزية تحتاج أمثلتها ومصطلحاتها المناسبة. تجنّب الترجمة الحرفية وتكرار الكلمات المفتاحية على حساب المعنى.' },
        { title: 'استخدم الكلمة المفتاحية كدليل لا كقالب', body: 'نتائج Semrush تساعدك على فهم الطلب، لكنها لا تكتب المقال عنك. اختر كلمة رئيسية ومرادفات قليلة، ثم ركّز على إجابة السؤال بوضوح بدلاً من تكرار العبارة في كل فقرة.' },
        { title: 'اختر الرابط الطبيعي داخل النص', body: 'أفضل موضع للرابط هو الجملة التي تجعل الانتقال منطقياً. إذا احتجت إلى حشو جملة لتبرير الرابط، فالصفحة المستهدفة أو زاوية المقال تحتاج مراجعة.' },
        { title: 'مراجعة قبل النشر', body: 'راجع صحة المعلومات وحقوق الصور والروابط والأصالة، ثم طابق النص مع متطلبات الناشر. توفّر الكتابة وتكلفتها ونطاق التعديلات تُحدّد ضمن العرض أو بعد التواصل مع الفريق.' },
      ],
      bullets: ['زاوية تخدم القارئ', 'صياغة مناسبة للغة والسوق', 'كلمة مفتاحية بلا حشو', 'متطلبات تحرير واضحة'],
      cta: 'ناقش متطلبات المحتوى',
    },
    en: {
      eyebrow: 'Content writing',
      title: 'A clear article before the link.',
      description: 'Plan useful Arabic and English guest post content with Linkaza. Learn what to include in your brief, editorial review and content service requirements.',
      intro: 'A link cannot rescue weak copy. Start with the reader’s question, then make the link a natural part of the answer.',
      sections: [
        { title: 'A clear brief comes first', body: 'Define the reader, the question you will answer, your angle and supporting sources. Include the destination page, publisher requirements and brand voice before agreeing on writing.' },
        { title: 'Write for the language and market', body: 'Arabic content needs natural phrasing and appropriate local context. English content needs its own examples and vocabulary. Literal translation and repeated keywords should never get in the way of meaning.' },
        { title: 'Use the keyword as evidence, not a template', body: 'Semrush data helps you understand demand, but it does not write the article. Choose a primary keyword and a few natural variants, then answer the reader’s question instead of repeating the phrase.' },
        { title: 'Place the link where it belongs', body: 'The best link location is the sentence where the next click makes sense. If the article needs filler to justify the link, review the angle or destination page before publication.' },
        { title: 'Review before publication', body: 'Check facts, image rights, links and originality, then compare the draft with the publisher’s requirements. Writing availability, pricing and revision scope depend on the offer or a discussion with the team.' },
      ],
      bullets: ['A reader-first angle', 'Language that fits the market', 'Keyword use without stuffing', 'Clear editorial requirements'],
      cta: 'Discuss your content brief',
    },
  },
  'strategy-builder': {
    ar: {
      eyebrow: 'تخطيط الحملات',
      title: 'لكل رابط مكان في الخطة.',
      description: 'ابنِ خطة باك لينك تبدأ من أهدافك وصفحاتك وجمهورك. إطار عملي لتحديد أولويات النشر والميزانية والمراجعة مع Linkaza.',
      intro: 'اجعل اختيار الناشر نتيجة لخطة واضحة: أين تريد الظهور، ولمن، وبأي محتوى؟',
      sections: [
        { title: 'اختر صفحات تستحق الأولوية', body: 'ابدأ بصفحات مكتملة وتخدم هدفاً واضحاً. دوّن لكل صفحة الجمهور والموضوع والنتيجة التي تريد قياسها، وحدّد ما يحتاج تحسيناً داخل موقعك قبل النشر الخارجي.' },
        { title: 'حلّل الفجوة بوعي', body: 'افحص أين يظهر منافسوك وكيف يقدّمون خبرتهم. ابحث عن موضوعات أو شرائح جمهور لم تخدمها بعد، ولا تعتبر كل موقع يربط بمنافسك اختياراً مناسباً لك تلقائياً.' },
        { title: 'قسّم الكلمات حسب نية البحث', body: 'افصل بين كلمات تجارية مثل شراء باك لينك وخدمة جيست بوست، وكلمات تعليمية مثل ما هو الباك لينك أو فحص الباك لينك. الصفحات التجارية تحتاج دليلاً على العرض، والصفحات التعليمية تحتاج شرحاً وصبراً.' },
        { title: 'ابنِ سايلو داخلياً قبل النشر', body: 'اربط صفحات السوق والأسعار وآلية العمل بالأدلة التعليمية وصفحات الحلول. هذا يساعد المستخدم على الانتقال بين السؤال والقرار، ويساعد محركات البحث على فهم علاقة الصفحات ببعضها.' },
        { title: 'وزّع التنفيذ وراجع القرار', body: 'ضع قائمة أولية بالناشرين وزوايا المقالات والتكلفة، ثم نفّذ على مراحل تناسب قدرتك على الإنتاج والمراجعة. استخدم النتائج لتعديل الاختيارات، وليس لافتراض عدد سحري من الروابط.' },
      ],
      bullets: ['هدف وصفحة لكل فرصة', 'فجوات مرتبطة بجمهورك', 'سايلو داخلي واضح', 'ميزانية قابلة للمراجعة'],
      cta: 'ابدأ تخطيط حملتك',
    },
    en: {
      eyebrow: 'Campaign strategy',
      title: 'Give every link a place in the plan.',
      description: 'Build a backlink plan around your goals, destination pages and audience. A practical framework for placement priorities, budgets and campaign reviews.',
      intro: 'Let a clear strategy guide publisher selection: where should you appear, who should you reach and what should you say?',
      sections: [
        { title: 'Prioritize pages with a purpose', body: 'Start with complete pages that serve a clear goal. Record the audience, subject and intended outcome for each one. Identify on-site improvements needed before investing in outside placements.' },
        { title: 'Interpret the competitor gap', body: 'Look at where competitors appear and how they share expertise. Find under-served topics or audiences, and assess each opportunity independently instead of copying every referring domain.' },
        { title: 'Group keywords by search intent', body: 'Separate commercial terms such as buy backlinks and guest posting service from educational terms such as what are backlinks or backlink checker. Commercial pages need offer clarity. Educational pages need patient explanation.' },
        { title: 'Build the internal silo first', body: 'Connect marketplace, pricing and how-it-works pages with guides and solution pages. This helps users move from question to decision and helps search engines understand how the pages relate.' },
        { title: 'Stage the work and review decisions', body: 'Map publishers, article angles and costs, then publish at a pace your team can brief and review properly. Let the evidence improve your next choices rather than aiming for a supposedly ideal link count.' },
      ],
      bullets: ['A goal for every destination', 'Audience-led opportunity analysis', 'A clear internal silo', 'A budget you can review'],
      cta: 'Start planning your campaign',
    },
  },
  analytics: {
    ar: {
      eyebrow: 'القياس والمتابعة',
      title: 'من رابط منشور إلى صورة أوضح.',
      description: 'تعرّف على كيفية متابعة حملات الباك لينك: فحص النشر، زيارات الإحالة، أداء صفحاتك في البحث وقراءة النتائج ضمن سياقها الصحيح.',
      intro: 'اعرف ما تم تنفيذه، وما تغيّر بعده، وما يمكنك الاستنتاج منه فعلاً.',
      sections: [
        { title: 'ابدأ بالتحقق من التسليم', body: 'افحص عنوان المقال ومحتواه والرابط المستهدف والنص الرابط وخصائصه. احتفظ بالرابط المباشر وتاريخ النشر وشروط الطلب لتسهيل أي مراجعة لاحقة.' },
        { title: 'راقب أكثر من إشارة', body: 'استخدم أدوات تحليلات موقعك لقراءة زيارات الإحالة والتفاعل والتحويلات، وSearch Console لمتابعة النقرات والظهور والصفحات والاستعلامات. هذه إشارات مختلفة، ولكل منها حدودها.' },
        { title: 'افصل التنفيذ عن الأداء', body: 'تنفيذ الطلب يعني أن المقال والرابط نُشرا وفق الشروط. الأداء يعني ما حدث بعد ذلك في الزيارات أو الظهور أو التحويلات. لا تخلط بين الأمرين عند تقييم الفريق أو الناشر.' },
        { title: 'راقب الصفحة المستهدفة', body: 'إذا كانت الصفحة المرتبطة بطيئة أو لا تجيب عن نية الزائر، فقد تضيع فائدة الإحالة. راجع معدل التفاعل، الأسئلة المتكررة، ووضوح الدعوة إلى الإجراء بعد كل حملة.' },
        { title: 'اقرأ التغيير في سياقه', body: 'دوّن تعديلات المحتوى والموقع والتغيّرات الموسمية خلال فترة القياس. تزامن تحسّن الترتيب مع حملة نشر لا يثبت وحده أن الحملة سبب التحسّن، ولا يضمن تكرار النتيجة.' },
      ],
      bullets: ['توثيق النشر الفعلي', 'قياس الزيارات والتفاعل', 'مراجعة الصفحة المستهدفة', 'قراءة واقعية للنتائج'],
      cta: 'ناقش قياس حملتك',
    },
    en: {
      eyebrow: 'Measurement & reporting',
      title: 'From a published link to a clearer picture.',
      description: 'Learn how to review backlink campaigns: verify published placements, measure referral traffic and understand search performance in its wider context.',
      intro: 'Know what was delivered, what changed afterwards and what the evidence actually lets you conclude.',
      sections: [
        { title: 'Verify the placement first', body: 'Review the article title, content, destination, anchor text and link attributes. Keep the published URL, date and order terms together to make later checks straightforward.' },
        { title: 'Read more than one signal', body: 'Use your own analytics for referral visits, engagement and conversions. Use Search Console for search clicks, impressions, pages and queries. These answer different questions and each has limitations.' },
        { title: 'Separate delivery from performance', body: 'Delivery means the article and link were published according to the terms. Performance means what happened later in visits, impressions or conversions. Keep those two judgments separate.' },
        { title: 'Review the destination page', body: 'If the linked page is slow or does not answer visitor intent, referral value can be wasted. Check engagement, repeated questions and the clarity of the call to action after each campaign.' },
        { title: 'Give changes their context', body: 'Record content updates, technical changes and seasonal factors during the reporting period. A ranking improvement after publication does not, by itself, establish that the placement caused it or that it will happen again.' },
      ],
      bullets: ['Documented publication checks', 'Traffic and engagement measures', 'Destination-page review', 'Evidence with proper context'],
      cta: 'Discuss your reporting needs',
    },
  },
  about: {
    ar: {
      eyebrow: 'عن Linkaza',
      title: 'روابط أفضل تبدأ بقرارات أوضح.',
      description: 'Linkaza منصة تجمع المشترين والناشرين لفرص الباك لينك والجيست بوست. تعرّف على رؤيتنا للجودة والمحتوى وتجربة النشر بالعربية والإنكليزية.',
      intro: 'نقرّب المسافة بين علامة لديها ما تقوله، وناشر يملك الجمهور المناسب لسماعها.',
      sections: [
        { title: 'مساحة تجمع طرفَي النشر', body: 'تربط Linkaza المشترين الباحثين عن فرص باك لينك وجيست بوست بالناشرين الذين يعرضون مواقعهم. يختار المشتري العرض الذي يناسبه، ويحتفظ الناشر بمعاييره وقراره التحريري.' },
        { title: 'العربية جزء من التجربة', body: 'السوق العربي يحتاج لغة واضحة وفهماً لاختلاف الجمهور بين الدول والقطاعات. لذلك نقدّم تجربة عربية وإنكليزية تساعدك على فهم الخيارات والتفاصيل بلغتك.' },
        { title: 'قرار الشراء يحتاج تفاصيل', body: 'المشتري لا يحتاج قائمة مواقع فقط. يحتاج أن يعرف اللغة والتخصص والسعر وشروط المحتوى ومدة التنفيذ وما سيحدث بعد الطلب. لذلك نضع هذه التفاصيل في قلب تجربة المقارنة.' },
        { title: 'الناشر ليس مجرد مساحة إعلانية', body: 'كل موقع يملك جمهوراً وسياقاً تحريرياً. نحترم أن الناشر يحدد شروطه ويملك قرار قبول المحتوى، لأن جودة المنصة تبدأ من جودة المواقع التي تقبل النشر.' },
        { title: 'الجودة تُشرح ولا تُختصر برقم', body: 'نؤمن بأن التخصص والجمهور والمحتوى وشروط النشر يجب أن تبقى في قلب القرار. قوة النطاق مفيدة للمقارنة، لكنها لا تغني عن قراءة الموقع ومعرفة ما ستشتريه.' },
      ],
      bullets: ['صلة حقيقية بالموضوع', 'تجربة عربية وإنكليزية', 'تفاصيل تساعد على الاختيار', 'احترام شروط الناشرين'],
      cta: 'تعرّف على السوق',
    },
    en: {
      eyebrow: 'About Linkaza',
      title: 'Better connections start with clearer choices.',
      description: 'Linkaza connects buyers and publishers for backlink and guest post opportunities. Learn about our approach to relevance, content and Arabic-English publishing.',
      intro: 'We bring together brands with something useful to say and publishers with the audience to hear it.',
      sections: [
        { title: 'A meeting point for publishing', body: 'Linkaza connects buyers looking for backlink and guest post opportunities with publishers offering placements. Buyers choose the offers that fit their plans; publishers retain their editorial standards and final publication decisions.' },
        { title: 'Arabic belongs at the center', body: 'Arabic-speaking markets deserve clear language and an understanding of how audiences differ across countries and industries. Our Arabic and English experience helps you evaluate the details in your own language.' },
        { title: 'Buying needs clear information', body: 'Buyers need more than a list of websites. They need language, topic, price, content requirements, delivery expectations and what happens after an order. Those details shape the comparison experience.' },
        { title: 'A publisher is not just ad space', body: 'Every website has an audience and editorial context. Publishers define their terms and keep the right to accept content, because marketplace quality starts with the websites willing to publish.' },
        { title: 'Quality needs an explanation', body: 'Relevance, readership, content and publication terms should sit at the center of a decision. Domain metrics are useful comparison signals, but they cannot replace reviewing a website and understanding the offer.' },
      ],
      bullets: ['Topical relevance', 'An Arabic and English experience', 'Details that support better decisions', 'Publisher terms respected'],
      cta: 'Get to know the marketplace',
    },
  },
  blog: {
    ar: {
      eyebrow: 'دليل Linkaza',
      title: 'اعرف أكثر. اختر أفضل.',
      description: 'أدلة عملية في الباك لينك والجيست بوست: تقييم جودة المواقع، كتابة موجز النشر وتخطيط ميزانية بناء الروابط، بالعربية والإنكليزية.',
      intro: 'معرفة عملية تساعدك على تقييم الفرص، وطرح الأسئلة الصحيحة، وبناء حملات أكثر وضوحاً.',
      sections: [
        { title: 'جودة الموقع', body: 'تعلّم كيف تفحص الصلة بالموضوع واتجاه الزيارات وأسلوب النشر، وكيف تضع مؤشرات قوة النطاق في حجمها الصحيح عند المقارنة.' },
        { title: 'المحتوى والجيست بوست', body: 'من اختيار زاوية المقال إلى مراجعة النسخة المنشورة: خطوات تساعدك على إعداد محتوى يناسب القارئ والناشر والصفحة التي تربط بها.' },
        { title: 'الكلمات والسايلو', body: 'افهم الفرق بين صفحة تجارية تستهدف شراء باك لينك وصفحة تعليمية تستهدف فحص الباك لينك أو معنى الجيست بوست. تنظيم النية يجعل المحتوى أوضح للمستخدم ومحركات البحث.' },
        { title: 'المنافسون في نتائج البحث', body: 'راقب ما يقدمه المنافسون: هل لديهم سوق واضح، أسعار مفهومة، شرح آلية العمل، أم مجرد مقالات عامة؟ استخدم هذه الفجوة لبناء صفحة تجيب عمّا لم يجيبوا عنه.' },
        { title: 'من القراءة إلى التنفيذ', body: 'كل دليل يجب أن يقود إلى خطوة واضحة: مقارنة موقع، إعداد موجز، مراجعة سعر أو فحص جودة. لذلك ترتبط الأدلة بصفحات السوق وآلية العمل والأسعار بدلاً من أن تبقى محتوى معزولاً.' },
        { title: 'التخطيط والميزانية', body: 'حدّد ما يدخل في تكلفة الحملة، وما يستحق الأولوية، وما تحتاج إلى قياسه قبل توسيع النشر. قرار واعٍ أفضل من شراء عدد غير مدروس من الروابط.' },
      ],
      bullets: ['أدلة عملية باللغة العربية', 'خطوات يمكنك تطبيقها', 'كلمات وسايلو أوضح', 'ربط بين المعرفة والتنفيذ', 'مصادر مباشرة عند الحاجة'],
      cta: 'اكتشف فرص النشر',
    },
    en: {
      eyebrow: 'The Linkaza journal',
      title: 'Know more. Choose better.',
      description: 'Practical backlink and guest posting guides in English and Arabic. Learn to evaluate publishers, prepare content briefs and plan a link building budget.',
      intro: 'Practical knowledge for evaluating opportunities, asking better questions and making clearer campaign decisions.',
      sections: [
        { title: 'Publisher quality', body: 'Learn to assess subject relevance, traffic trends and publishing patterns, and put third-party domain scores in their proper place when comparing websites.' },
        { title: 'Content and guest posting', body: 'From choosing an article angle to reviewing the live placement, prepare content that fits the reader, the publication and the destination you are linking to.' },
        { title: 'Keywords and content silos', body: 'Understand the difference between a commercial page targeting buy backlinks and an educational guide targeting backlink checker or what is guest posting. Clear intent makes content easier for users and search engines.' },
        { title: 'Competitors in the search results', body: 'Look at what competitors provide: a clear marketplace, pricing, workflow guidance or only general blog posts. Use that gap to build pages that answer what others leave unclear.' },
        { title: 'From reading to action', body: 'Each guide should lead to a useful next step: comparing a publisher, preparing a brief, reviewing cost or checking quality. That is why the guides connect back to marketplace, how-it-works and pricing pages instead of standing alone.' },
        { title: 'Planning and budgets', body: 'Understand the full campaign cost, decide what deserves priority and define your measures before expanding. A considered selection is more useful than an arbitrary target number of links.' },
      ],
      bullets: ['Practical Arabic and English guides', 'Steps you can apply', 'Clearer keywords and silos', 'Knowledge connected to action', 'Direct sources where they matter'],
      cta: 'Explore publishing opportunities',
    },
  },
  affiliate: {
    ar: {
      eyebrow: 'شراكات وإحالات',
      title: 'توصية تبدأ بفهم جمهورك.',
      description: 'تعرّف على برنامج شراكات Linkaza والإحالات. ناقش ملاءمة جمهورك وشروط العمولة والتتبّع والدفع مع الفريق قبل بدء التعاون.',
      intro: 'إذا كان جمهورك يبحث عن فرص نشر وباك لينك، لنتحدث عن شراكة تقدّم له قيمة واضحة.',
      sections: [
        { title: 'شاركنا طبيعة جمهورك', body: 'عرّفنا بموقعك أو قناتك ونوع المحتوى الذي تقدّمه والأسواق التي تصل إليها. يساعد هذا السياق على تقييم ملاءمة التعاون وطريقة تقديم Linkaza لجمهورك.' },
        { title: 'اتفق على التفاصيل أولاً', body: 'ناقش معدل العمولة والطلبات المؤهلة وآلية الإسناد وشروط الدفع مباشرة مع الفريق. تُحدّد شروط الشراكة خلال التقديم، فلا تفترض نسبة أو استحقاقاً قبل الاتفاق.' },
        { title: 'قدّم الخدمة لمن يحتاجها فعلاً', body: 'أفضل شريك هو من يملك جمهوراً يسأل عن السيو، الجيست بوست، بناء الروابط أو نمو المواقع. لا نبحث عن إحالات كثيرة فقط؛ نبحث عن إحالات تفهم ما تشتريه.' },
        { title: 'استخدم مواد شرح دقيقة', body: 'اربط جمهورك بصفحات السوق وآلية العمل والأسعار والأسئلة الشائعة بدلاً من وعود عامة. الشرح الواضح يقلل التسجيلات غير المناسبة ويحسّن جودة العملاء المحتملين.' },
        { title: 'قِس جودة الإحالة لا عددها فقط', body: 'راقب نوع الأسئلة التي تأتي من جمهورك، وهل يفهمون الفرق بين السوق، السعر، المحتوى، وسياسات الروابط. الإحالة الجيدة تصل وهي تعرف ما تحتاجه وتطرح سؤالاً محدداً.' },
        { title: 'توصية واضحة وشفافة', body: 'اشرح الخدمة كما هي وافصح لجمهورك عن علاقتك التجارية. استخدم أمثلة مفيدة وتجنّب الوعود بترتيب أو نتائج غير مضمونة.' },
      ],
      bullets: ['ملاءمة بين الخدمة والجمهور', 'شروط شراكة متفق عليها', 'مواد شرح دقيقة', 'جودة إحالات قابلة للمراجعة', 'توصية واضحة للمتابعين'],
      cta: 'تواصل بشأن الشراكة',
    },
    en: {
      eyebrow: 'Partners & referrals',
      title: 'A recommendation your audience understands.',
      description: 'Explore a Linkaza referral partnership. Discuss audience fit, commission terms, attribution and payment requirements with the team before getting started.',
      intro: 'If your audience is looking for backlink and publishing opportunities, let’s discuss a partnership with a clear purpose.',
      sections: [
        { title: 'Tell us about your audience', body: 'Share your website or channel, the content you create and the markets you reach. This helps establish whether a partnership fits and how to introduce Linkaza usefully.' },
        { title: 'Agree on the details first', body: 'Discuss commission rates, eligible orders, attribution and payment terms with the team. Partnership conditions are defined during the application process; do not assume a rate or entitlement before agreement.' },
        { title: 'Recommend it to the right audience', body: 'The strongest partner has an audience asking about SEO, guest posting, link building or website growth. We care less about raw referral volume and more about referrals that understand what they are buying.' },
        { title: 'Use accurate explanation pages', body: 'Point your audience to the marketplace, how-it-works, pricing and FAQ pages instead of broad claims. Clear explanation reduces poor-fit signups and improves lead quality.' },
        { title: 'Measure referral quality, not volume alone', body: 'Review the questions your audience sends. Do they understand the marketplace, pricing, content requirements and link policies? A strong referral arrives with a specific need, not just curiosity.' },
        { title: 'Keep the recommendation transparent', body: 'Describe the service accurately and disclose your commercial relationship to your audience. Use useful examples and avoid promising search rankings or outcomes that cannot be guaranteed.' },
      ],
      bullets: ['A relevant audience', 'Agreed partnership terms', 'Accurate explanation pages', 'Reviewable referral quality', 'A transparent recommendation'],
      cta: 'Discuss a partnership',
    },
  },
  support: {
    ar: {
      eyebrow: 'مركز المساعدة',
      title: 'لنصل إلى إجابة واضحة.',
      description: 'تواصل مع دعم Linkaza للمساعدة بشأن حسابك وطلبات النشر وشروط العروض. اعرف التفاصيل التي تسرّع فهم استفسارك ومراجعته.',
      intro: 'سؤال عن عرض، أو خطوة في طلب، أو مشكلة في حسابك؟ أرسل التفاصيل إلى support@linkaza.com.',
      sections: [
        { title: 'قبل إنشاء الطلب', body: 'أرسل رابط العرض وما تريد التأكد منه: متطلبات المقال، نوع الرابط، مدة التنفيذ أو ما يشمله السعر. وضوح السؤال يساعدنا على توجيهك للمعلومة المناسبة.' },
        { title: 'بخصوص طلب قائم', body: 'اذكر رقم الطلب والبريد المرتبط بالحساب ووصفاً مختصراً للمشكلة. أضف رابط المقال إن كان منشوراً، والفرق بين ما اتُّفق عليه وما ظهر فعلياً.' },
        { title: 'لأسئلة الناشرين', body: 'إذا كنت تضيف موقعاً، أرسل رابط الموقع واللغة والتخصص والسعر المقترح وأي شروط نشر مهمة. هذه التفاصيل تساعد الفريق على مراجعة العرض بسرعة أكبر.' },
        { title: 'لأسئلة المحتوى', body: 'إذا كان سؤالك عن كتابة مقال أو موجز جيست بوست، أرسل الصفحة المستهدفة والجمهور المطلوب والكلمة أو الموضوع الأساسي ومتطلبات الناشر إن وجدت.' },
        { title: 'للمشاكل التقنية أو الروابط', body: 'إذا واجهت صفحة لا تفتح، رابطاً لا يعمل، أو مشكلة في تبديل اللغة، أرسل الرابط الكامل والخطوة التي سبقت المشكلة. التفاصيل الصغيرة تختصر وقت الفحص والإصلاح.' },
        { title: 'خصوصية حسابك أولاً', body: 'لا ترسل كلمة المرور أو معلومات الدفع الكاملة. للاستفسارات المتعلقة بالبيانات الشخصية أو النصوص القانونية يمكنك التواصل مباشرة عبر legal@linkaza.com.' },
      ],
      bullets: ['رقم الطلب عند توفره', 'وصف واضح لما تحتاجه', 'روابط أو تفاصيل تساعد على المراجعة', 'خطوات إعادة المشكلة عند الحاجة', 'لا ترسل كلمات المرور'],
      cta: 'راسل فريق الدعم',
    },
    en: {
      eyebrow: 'Help & support',
      title: 'Let’s get you a clear answer.',
      description: 'Contact Linkaza support about your account, placement orders or publisher terms. Find the details to include so the team can understand your question.',
      intro: 'A question about an offer, an order step or your account? Send the details to support@linkaza.com.',
      sections: [
        { title: 'Before placing an order', body: 'Include the offer URL and what you want to clarify: article requirements, link attributes, delivery timeline or what the price covers. A specific question makes it easier to find the right information.' },
        { title: 'For an existing order', body: 'Provide the order reference, your account email and a short description of the issue. If the article is live, include its URL and explain any difference from the agreed requirements.' },
        { title: 'For publisher questions', body: 'If you are adding a website, send the website URL, language, topic focus, proposed price and important publishing terms. These details help the team review the offer faster.' },
        { title: 'For content questions', body: 'If your question concerns article writing or a guest post brief, include the destination page, target audience, main keyword or topic and any publisher requirements you already know.' },
        { title: 'For technical or link issues', body: 'If a page does not open, a link fails or language switching behaves unexpectedly, send the full URL and the step that came before the issue. Small details shorten troubleshooting time.' },
        { title: 'Keep account details private', body: 'Do not send passwords or full payment details. For personal data requests or questions about the legal documents, contact legal@linkaza.com directly.' },
      ],
      bullets: ['An order reference if available', 'A clear description of the issue', 'Relevant URLs or supporting details', 'Steps to reproduce when needed', 'Do not send passwords'],
      cta: 'Email support',
    },
  },
  contact: {
    ar: {
      eyebrow: 'تواصل معنا',
      title: 'فرصتك التالية تبدأ بمحادثة.',
      description: 'تواصل مع فريق Linkaza بشأن الباك لينك والجيست بوست وخدمات المحتوى والانضمام كناشر. أرسل متطلباتك إلى support@linkaza.com.',
      intro: 'أخبرنا بما تعمل عليه، وساعدنا على فهم الجمهور والسوق والهدف الذي تريد الوصول إليه.',
      sections: [
        { title: 'للحملات وخدمات المحتوى', body: 'شارك رابط موقعك ولغة الحملة والسوق المستهدف والميزانية التقريبية. أضف الصفحات التي تريد الترويج لها وأي شروط مهمة لعلامتك.' },
        { title: 'للناشرين والشركاء', body: 'أرسل رابط موقعك أو قناتك وتخصصها ولغة محتواها. وضّح إن كنت ترغب في عرض فرص نشر أو مناقشة شراكة إحالة.' },
        { title: 'للوكالات ومستشاري السيو', body: 'اذكر عدد العملاء أو الحملات التي تريد إدارتها، اللغات المطلوبة، وكيف تراجع فرص الباك لينك حالياً. هذا يساعدنا على اقتراح طريقة استخدام مناسبة للفريق.' },
        { title: 'للملاحظات على الموقع', body: 'إذا وجدت مشكلة في صفحة أو رابط أو لغة أو بيانات، أرسل رابط الصفحة ولقطة شاشة إن أمكن. الملاحظة المحددة أسرع في المعالجة من وصف عام.' },
        { title: 'للاستفسارات قبل التسجيل', body: 'إذا لم تكن متأكداً هل Linkaza مناسبة لك، اشرح نوع موقعك أو عملائك، واللغة المستهدفة، والصفحات التي تريد دعمها. سنرد بما تحتاج معرفته قبل إنشاء الطلب الأول.' },
        { title: 'للدعم والاستفسارات', body: 'راسل support@linkaza.com للاستفسارات العامة والطلبات. وللشروط والخصوصية وطلبات البيانات الشخصية، استخدم legal@linkaza.com.' },
      ],
      bullets: ['رابط الموقع أو المشروع', 'السوق واللغة المستهدفان', 'ملخص واضح لما تحتاجه', 'سؤال ما قبل التسجيل', 'لقطة شاشة عند وجود مشكلة'],
      cta: 'ابدأ المحادثة',
    },
    en: {
      eyebrow: 'Contact Linkaza',
      title: 'Your next opportunity starts here.',
      description: 'Contact Linkaza about backlinks, guest posts, content requirements or becoming a publisher. Send your project details to support@linkaza.com.',
      intro: 'Tell us what you are working on, the audience you want to reach and the outcome you have in mind.',
      sections: [
        { title: 'Campaigns and content', body: 'Share your website, campaign language, target market and approximate budget. Add your priority destination pages and any important brand requirements.' },
        { title: 'Publishers and partners', body: 'Send your website or channel, subject focus and content language. Let us know whether you want to offer publishing opportunities or discuss a referral partnership.' },
        { title: 'Agencies and SEO consultants', body: 'Mention the number of clients or campaigns you want to manage, the required languages and how you review backlink opportunities today. This helps us suggest a practical workflow.' },
        { title: 'Website feedback', body: 'If you find a page, link, language or data issue, send the page URL and a screenshot when possible. Specific reports are easier to review than broad descriptions.' },
        { title: 'Questions before signup', body: 'If you are not sure whether Linkaza fits, describe your website or clients, the target language and the pages you want to support. We can reply with the information you need before the first order.' },
        { title: 'Support and other questions', body: 'Email support@linkaza.com for general enquiries and order questions. For terms, privacy or personal data requests, use legal@linkaza.com.' },
      ],
      bullets: ['Your website or project', 'Your target language and market', 'A short description of your needs', 'Pre-signup questions', 'A screenshot for website issues'],
      cta: 'Start a conversation',
    },
  },
  'how-it-works': {
    ar: {
      eyebrow: 'كيف تعمل Linkaza',
      title: 'من الفكرة إلى المقال المنشور.',
      description: 'تعرّف على آلية عمل Linkaza خطوة بخطوة: شحن الرصيد، اختيار موقع باك لينك أو جيست بوست، إرسال الطلب، متابعة النشر، ودورة عمل الناشرين.',
      intro: 'هذه هي الخطوات العملية داخل Linkaza. تعرف متى تشحن الرصيد، ماذا ترسل في الطلب، وكيف تراجع الرابط بعد النشر.',
      sections: [
        { title: '1. أنشئ الحساب واشحن الرصيد', body: 'ابدأ بإنشاء حساب في لوحة Linkaza. قبل شراء الباك لينك تحتاج إلى رصيد في محفظتك؛ من خيار تعبئة الرصيد تستطيع تحديد المبلغ والتواصل مع الفريق لإتمام الشحن حسب الطريقة المتاحة في حسابك.' },
        { title: '2. اختر الموقع وراجع العرض', body: 'ابحث في السوق عن موقع يناسب موضوعك وجمهورك ولغة حملتك. راجع السعر، التخصص، الدولة المستهدفة، مؤشرات السيو، شروط المحتوى، نوع الرابط، ومدة بقاء النشر قبل اتخاذ القرار.' },
        { title: '3. جهّز الطلب والمحتوى', body: 'حدّد الصفحة المستهدفة والنص الرابط Anchor Text وأرفق المقال أو متطلبات الكتابة إذا كانت متاحة ضمن العرض. كلما كان الموجز أوضح، أصبح التنفيذ أسرع وأسهل على الناشر والمراجع.' },
        { title: '4. يتم حجز قيمة الطلب', body: 'عند تأكيد الطلب تُخصم قيمة الخدمة من رصيدك وتُحجز داخل المنصة أثناء التنفيذ. إذا رفض الناشر الطلب، أو لم يطابق التسليم شروط الطلب، يُراجع الرصيد وفق قواعد الطلب.' },
        { title: '5. تابع حالة الطلب', body: 'يمر الطلب عادة بمراحل مثل Pending للمراجعة، Approved عند قبول الناشر، Published بعد نشر الرابط، وSettled بعد المراجعة النهائية. هذه الحالات تساعدك على معرفة أين وصل التنفيذ وما المطلوب منك.' },
        { title: '6. راجع المقال عند النشر', body: 'بعد قبول الناشر وتنفيذ الطلب، افتح رابط المقال وتحقق من العنوان، النص، الرابط، الصفحة المستهدفة وخصائص الرابط وفق الاتفاق. احتفظ بمرجع الطلب وتواصل مع الدعم عند وجود اختلاف يحتاج مراجعة.' },
        { title: 'للناشرين: أضف موقعك بشروط واضحة', body: 'إذا كنت تملك موقعاً، يمكنك إضافة بياناته من لوحة التحكم: الرابط، اللغة، السعر، التصنيفات، النيتشات، وشروط النشر. بعد المراجعة تظهر الفرصة للمشترين المناسبين، وتستقبل الطلبات وفق دورة العمل نفسها.' },
      ],
      bullets: ['اشحن الرصيد قبل الطلب', 'اختر موقعاً مناسباً', 'اعتمد تفاصيل المحتوى والرابط', 'تابع الحالة حتى النشر', 'راجع ما تم تسليمه'],
      cta: 'ابدأ طلبك الأول',
    },
    en: {
      eyebrow: 'How Linkaza works',
      title: 'From an idea to a published article.',
      description: 'Learn how Linkaza works step by step: top up your balance, choose a backlink or guest post publisher, submit an order, follow publication and understand the publisher workflow.',
      intro: 'These are the practical steps inside Linkaza: when to top up, what to send with the order and how to review the link after publication.',
      sections: [
        { title: '1. Create an account and top up your balance', body: 'Start by creating an account in the Linkaza dashboard. Before buying a backlink, you need funds in your wallet. The top-up flow lets you define the amount and contact the team to complete the balance charge according to the options available in your account.' },
        { title: '2. Choose a publisher and review the offer', body: 'Search the marketplace for a website that matches your subject, audience and campaign language. Review pricing, niche, target country, SEO metrics, content requirements, link attributes and publication duration before ordering.' },
        { title: '3. Prepare the order and content', body: 'Specify your destination page and anchor text. Provide the article or a writing brief where that service is available. The clearer the brief, the easier it is for the publisher and reviewer to deliver the placement correctly.' },
        { title: '4. The order amount is reserved', body: 'When you confirm an order, the service amount is deducted from your balance and held while the work moves through delivery. If the publisher rejects it or delivery does not match the agreed terms, the balance is handled according to the order rules.' },
        { title: '5. Follow the order status', body: 'An order can move through states such as Pending for review, Approved after publisher acceptance, Published when the link is live and Settled after final review. These states show where the work stands and what needs attention.' },
        { title: '6. Review the live placement', body: 'Once the publisher completes the order, open the article and check the title, content, link, destination page and link attributes against the agreement. Keep the order reference and contact support about any discrepancy.' },
        { title: 'For publishers: list your website clearly', body: 'If you own a website, you can submit its URL, language, price, categories, niches and publishing terms from the dashboard. After review, your offer can appear to relevant buyers and follow the same order lifecycle.' },
      ],
      bullets: ['Top up before ordering', 'Choose a relevant website', 'Confirm content and link details', 'Follow the order status', 'Review the published result'],
      cta: 'Start your first order',
    },
  },
  'guest-posts': {
    ar: {
      eyebrow: 'الجيست بوست',
      title: 'خبرتك، أمام جمهور جديد.',
      description: 'اكتشف فرص جيست بوست عربية وإنكليزية مع Linkaza. اختر مواقع تناسب تخصصك وانشر محتوى مفيداً يعرّف القرّاء بخبرتك وعلامتك.',
      intro: 'الجيست بوست ليس مكاناً لإخفاء رابط داخل نص ضعيف. المقال يجب أن يجيب عن سؤال القارئ، والرابط يجب أن يكمل الفقرة التي يظهر فيها.',
      sections: [
        { title: 'ما هو الجيست بوست؟', body: 'الجيست بوست مقال يقدّمه كاتب أو علامة للنشر على موقع آخر. تختلف شروطه بين الناشرين؛ وقد يتضمن رابطاً ذا صلة إلى موقعك ضمن المحتوى أو التعريف بالكاتب بحسب الاتفاق.' },
        { title: 'اختر زاوية تخصّ هذا الجمهور', body: 'اقرأ مقالات الموقع قبل إعداد الموجز. اقترح موضوعاً يكمّل تغطيته، مع تجربة أو مثال أو تحليل أصلي. المقال المصمم لموقع بعينه أكثر ملاءمة من نص عام يُرسل إلى الجميع.' },
        { title: 'اكتب موجزاً يحترم القارئ', body: 'حدّد القارئ، السؤال الرئيسي، النقاط التي يجب تغطيتها، المصادر، نبرة العلامة، والصفحة المستهدفة. لا تجعل المقال يدور حول الرابط وحده؛ اجعل الرابط امتداداً لفكرة تساعد القارئ.' },
        { title: 'اختر Anchor Text طبيعي', body: 'النص الرابط الجيد يشرح الوجهة من دون حشو. استخدم عبارات وصفية أو اسم العلامة أو عنوان الصفحة عندما يكون ذلك مناسباً، وتجنب تكرار كلمة مفتاحية تجارية بشكل يبدو خارج سياق الجملة.' },
        { title: 'اتفق على تفاصيل النشر', body: 'راجع قواعد التحرير ونوع الرابط وظهور المقال ومدته وحقوق استخدام المحتوى. عندما يكون النشر مدفوعاً، يجب توضيح العلاقة واستخدام وسم sponsored أو nofollow وفق إرشادات Google.' },
        { title: 'راجع التسليم على الهاتف وسطح المكتب', body: 'بعد النشر، افتح المقال من أكثر من جهاز. تأكد أن الرابط يعمل، وأن المقال قابل للقراءة، وأن الصور والتنسيق لا يضعفان التجربة. ثم احتفظ برابط المقال وتاريخ النشر ضمن سجل حملتك.' },
      ],
      bullets: ['موضوع مرتبط بتخصص الناشر', 'محتوى أصلي وله غرض', 'Anchor Text طبيعي', 'شروط تحرير وروابط واضحة'],
      cta: 'اكتشف فرص الجيست بوست',
    },
    en: {
      eyebrow: 'Guest posting',
      title: 'Your expertise. A new audience.',
      description: 'Explore Arabic and English guest post opportunities with Linkaza. Choose relevant publishers and create useful articles that introduce readers to your expertise.',
      intro: 'A guest post is not a place to hide a link in weak copy. The article should answer a reader’s question, and the link should fit the paragraph where it appears.',
      sections: [
        { title: 'What is a guest post?', body: 'A guest post is an article contributed by an outside author or brand to another publication. Publisher requirements vary; a relevant link may appear in the content or author information, depending on the agreement.' },
        { title: 'Choose an angle for this readership', body: 'Read the publication before preparing your brief. Propose a topic that complements its coverage, with an original example, experience or analysis. An article written for a particular audience is more useful than a generic draft sent everywhere.' },
        { title: 'Write a reader-first brief', body: 'Define the reader, central question, outline, sources, brand voice and destination page. Do not make the article revolve around the link alone; let the link continue a useful idea for the reader.' },
        { title: 'Use natural anchor text', body: 'Good anchor text describes the destination without stuffing. Brand terms, page titles and descriptive phrases can all work when they fit the sentence. Avoid repeating a commercial keyword where it feels unnatural.' },
        { title: 'Agree on the publishing details', body: 'Review editorial rules, link attributes, article visibility, duration and content rights. Paid placements should disclose the relationship and use sponsored or nofollow link attributes in line with Google’s guidance.' },
        { title: 'Review delivery on mobile and desktop', body: 'After publication, open the article on more than one device. Confirm the link works, the article is readable, and imagery or formatting does not weaken the experience. Keep the live URL and publication date in your campaign record.' },
      ],
      bullets: ['A topic relevant to the publisher', 'Original content with a purpose', 'Natural anchor text', 'Clear editorial and link requirements'],
      cta: 'Find guest post opportunities',
    },
  },
  'quality-standards': {
    ar: {
      eyebrow: 'اختيار الجودة',
      title: 'جودة الباك لينك ليست رقماً واحداً.',
      description: 'تعرّف على معايير تقييم مواقع الباك لينك والجيست بوست: الصلة بالموضوع والجمهور والزيارات وجودة التحرير وشروط النشر قبل الشراء.',
      intro: 'استخدم هذه المعايير قبل الشراء. موقع أصغر لكنه قريب من مجال عملك قد يكون أفضل من موقع كبير لا يقرأه جمهورك.',
      sections: [
        { title: 'صلة يمكن تفسيرها', body: 'هل يتناول الموقع موضوعات قريبة من نشاطك؟ وهل يضيف المقال المقترح شيئاً لقرّائه؟ افحص اللغة والجمهور وأمثلة النشر، ولا تكتفِ بتطابق كلمة في اسم التصنيف.' },
        { title: 'بيانات تقرؤها في سياقها', body: 'راجع مصدر الزيارات واتجاهها والدول والصفحات المهمة. اسأل عن مصدر الأرقام وتاريخها، وميّز بين القياسات المباشرة والتقديرات. لا يعني ارتفاع DA أو DR أن كل فرصة في الموقع مناسبة.' },
        { title: 'جودة تحرير حقيقية', body: 'اقرأ مقالات حديثة من الموقع. هل فيها عناوين واضحة، أمثلة، مصادر، وروابط داخلية مفيدة؟ هل المقالات قابلة للعثور من التصنيفات أم تبدو كصفحات معزولة؟' },
        { title: 'تجربة مستخدم لا تطرد القارئ', body: 'افتح الموقع على الهاتف. راقب سرعة التحميل، كثافة الإعلانات، وضوح النص، وحجم الخط. موقع يملك مؤشرات جيدة لكنه مزعج للقراءة قد لا يكون المكان الأفضل لعلامتك.' },
        { title: 'تحرير وشروط واضحة', body: 'افحص جودة المقالات وتنوعها وظهور المحتوى في أقسام الموقع. قبل الطلب، تأكد من خصائص الرابط ومتطلبات المراجعة ومدة النشر وما يحدث إذا خالف التسليم الشروط المتفق عليها.' },
        { title: 'التزام بسياسات البحث', body: 'النشر المدفوع يحتاج وضوحاً في العلاقة ووسماً مناسباً للرابط عند الحاجة. لا تستخدم شراء الباك لينك كوعود ترتيب، بل كجزء من استراتيجية محتوى وعلاقات نشر أوسع.' },
      ],
      bullets: ['التخصص والجمهور', 'مصدر البيانات وحداثتها', 'جودة المحتوى وتجربة القراءة', 'وضوح العرض والالتزام بسياسات البحث'],
      cta: 'قارن فرص النشر',
    },
    en: {
      eyebrow: 'Evaluating quality',
      title: 'Backlink quality is more than one score.',
      description: 'Evaluate backlink and guest post publishers through relevance, audience, traffic evidence, editorial quality and clear placement terms before purchasing.',
      intro: 'Use these checks before buying. A smaller site close to your market may be better than a large site your customers do not read.',
      sections: [
        { title: 'Relevance you can explain', body: 'Does the website cover subjects close to your business? Would the proposed article help its readers? Review language, audience and published examples instead of relying on a matching category label.' },
        { title: 'Data in its proper context', body: 'Review traffic sources, trends, audience countries and important pages. Ask where figures come from and when they were updated. Distinguish direct measurements from estimates; a higher DA or DR does not make every placement a good fit.' },
        { title: 'Real editorial quality', body: 'Read recent articles. Look for clear headings, examples, sources and useful internal links. Check whether articles are discoverable through categories or feel isolated. Editorial quality affects reader trust and the value of your placement.' },
        { title: 'A user experience that keeps readers', body: 'Open the publication on mobile. Check load speed, ad density, readability and font size. A site can have attractive metrics and still be a poor environment for your brand if the reading experience is weak.' },
        { title: 'Editorial quality and clear terms', body: 'Read recent articles and check how content is linked from the publication’s sections. Before ordering, confirm link attributes, revision requirements, placement duration and the process if delivery differs from the agreement.' },
        { title: 'Search policy awareness', body: 'Paid publication needs clear disclosure and appropriate link qualification where required. Do not present backlink buying as a ranking promise; use it as one part of a broader content and publisher relationship strategy.' },
      ],
      bullets: ['Subject and audience relevance', 'Data sources and freshness', 'Editorial quality and reading experience', 'Clear terms and search policy awareness'],
      cta: 'Compare publishing opportunities',
    },
  },
  faq: {
    ar: {
      eyebrow: 'الأسئلة الشائعة',
      title: 'تفاصيل تستحق أن تعرفها.',
      description: 'إجابات عن Linkaza والباك لينك والجيست بوست: اختيار الموقع، الأسعار، المحتوى، مدد النشر والفرق بين تنفيذ الطلب ونتائج محركات البحث.',
      intro: 'افهم طريقة العمل وما تحتاج إلى مراجعته قبل اختيار أول عرض.',
      sections: [
        { title: 'هل تشمل الأسعار كتابة المقال؟', body: 'يعتمد ذلك على العرض. بعض فرص النشر تتطلب مقالاً جاهزاً، وقد تتوفر الكتابة كخدمة اختيارية. راجع تفاصيل الناشر وتكلفة المحتوى قبل اعتماد الطلب.' },
        { title: 'كم يستغرق النشر؟ وما مدة بقاء الرابط؟', body: 'تختلف مدة التنفيذ ومدة بقاء النشر بحسب الناشر والعرض. راجعهما قبل الشراء ولا تفترض مدة موحّدة. عند وجود مشكلة، يعتمد تقييمها على شروط الطلب وما تم تسليمه.' },
        { title: 'هل تضمن Linkaza ترتيباً في Google؟', body: 'لا. ترتيب البحث يتأثر بعوامل متعددة ولا تضمن Linkaza مركزاً محدداً أو زيادة في الزيارات. وعند شراء النشر المدفوع، راجع الإفصاح وخصائص الرابط المناسبة ضمن شروط العرض.' },
        { title: 'هل أحتاج حساباً قبل تصفح السوق؟', body: 'يمكنك رؤية فكرة السوق والعروض التجريبية من الموقع، لكن تفاصيل الشراء وإرسال الطلبات تتم من لوحة Linkaza. إنشاء الحساب يسمح لك بتعبئة الرصيد، اختيار العرض، ومتابعة حالة الطلب.' },
        { title: 'ماذا أرسل عند طلب جيست بوست؟', body: 'أرسل الصفحة المستهدفة، النص الرابط، فكرة المقال أو المسودة، لغة الحملة، وأي شروط خاصة بعلامتك. إذا كان العرض يتطلب محتوى جاهزاً، راجع المقال قبل الإرسال لتقليل التعديلات.' },
        { title: 'هل يستطيع الناشر رفض الطلب؟', body: 'نعم. الناشر يحتفظ بقراره التحريري وقد يرفض موضوعاً لا يناسب موقعه أو شروطه. في هذه الحالة تُراجع حالة الطلب والرصيد وفق آلية المنصة وشروط العرض.' },
      ],
      bullets: ['الناشر يحدّد سعر العرض', 'شروط كل طلب تُراجع قبل الشراء', 'الحساب مطلوب لإدارة الطلب', 'الدعم متاح لاستفساراتك'],
      cta: 'لديك سؤال آخر؟ تواصل معنا',
    },
    en: {
      eyebrow: 'Frequently asked questions',
      title: 'Details to check before you buy.',
      description: 'Answers about Linkaza backlinks and guest posts: publisher selection, pricing, content, publication periods and what search results cannot be guaranteed.',
      intro: 'Understand the process and the details to review before choosing your first offer.',
      sections: [
        { title: 'Does the price include an article?', body: 'It depends on the offer. Some placements require a ready-to-publish article; writing may be available as an optional service. Review the publisher requirements and content costs before confirming your order.' },
        { title: 'How long does publication take, and how long does it stay live?', body: 'Delivery time and publication duration vary by publisher and offer. Check both before buying rather than assuming a standard period. Any delivery issue is assessed against the agreed order terms.' },
        { title: 'Does Linkaza guarantee Google rankings?', body: 'No. Search performance depends on many factors, and Linkaza does not guarantee a position or traffic increase. For paid placements, review the disclosure and appropriate link attributes as part of the offer.' },
        { title: 'Do I need an account before using the marketplace?', body: 'You can understand the marketplace and preview sample offers from the public website, but purchasing and order submission happen in the Linkaza dashboard. An account lets you add balance, choose an offer and follow order status.' },
        { title: 'What should I send for a guest post order?', body: 'Send the destination page, anchor text, article idea or draft, campaign language and any brand requirements. If the offer requires ready content, review the article before sending it to reduce avoidable revisions.' },
        { title: 'Can a publisher reject an order?', body: 'Yes. Publishers keep editorial control and may reject a topic that does not fit their website or terms. In that case, the order and balance are reviewed according to the platform workflow and offer terms.' },
      ],
      bullets: ['Publishers set placement prices', 'Review each order’s terms before buying', 'An account is needed to manage orders', 'Contact support for specific questions'],
      cta: 'Ask us another question',
    },
  },
  terms: {
    ar: {
      eyebrow: 'آخر تحديث: 23 أكتوبر 2025',
      title: 'الشروط والأحكام',
      description: 'الشروط التي تحكم استخدام موقع Linkaza ومنصته وخدماته، بما في ذلك الحسابات والطلبات والمدفوعات والتزامات المشترين والناشرين.',
      intro: 'تحكم هذه الشروط وصولك إلى موقع Linkaza ومنصته وخدماته، المملوكة والمشغّلة من قِبل Linkaza. باستخدام الخدمة، فإنك توافق على الالتزام بهذه الشروط. إذا كنت لا توافق عليها، فلا يجوز لك استخدام الخدمة.',
      sections: [
        { title: '1. التعريفات', body: '«الخدمة» تعني منصة Linkaza وموقعها وجميع الخدمات المرتبطة بها. «المستخدم» يعني أي فرد أو جهة تنشئ حساباً وتستخدم الخدمة، ويشمل المشترين والناشرين. «مكان النشر» يعني نشر محتوى يتضمن باك لينك على موقع ناشر. «المحتوى» يشمل المقالات والنصوص والصور والمواد المقدّمة أو المنشأة فيما يتصل بالنشر.' },
        { title: '2. تسجيل الحساب واستخدامه', body: 'يتطلب استخدام الخدمة التسجيل بمعلومات دقيقة وحديثة وكاملة. أنت مسؤول عن حماية كلمة مرورك وعن الأنشطة التي تتم عبر حسابك، وعليك إخطارنا فور علمك بخرق أمني أو استخدام غير مصرّح به. يجب أن يكون عمرك 18 عاماً على الأقل لاستخدام الخدمة.' },
        { title: '3. الخدمة', body: 'تقدّم Linkaza سوقاً يربط المشترين الباحثين عن باك لينك بالناشرين الراغبين في بيع فرص نشر على مواقعهم. قد تتوفر خدمة كتابة محتوى اختيارية لتسهيل النشر. نحتفظ بحق رفض تقديم الخدمة لأي شخص لأي سبب وفي أي وقت.' },
        { title: '4. المدفوعات والأرصدة والاسترداد', body: 'تعمل الخدمة بنظام الدفع بحسب الاستخدام، من خلال رصيد الحساب أو الدفع لكل طلب. يحدّد الناشرون أسعار النشر وتُعرض في السوق. تُدرس طلبات الاسترداد حالةً بحالة؛ وقد يُقبل الاسترداد عند عدم تنفيذ النشر أو عدم مطابقته للمتطلبات المتفق عليها أو إزالة الرابط خلال فترة الضمان المحددة في العرض، مثل 12 شهراً إذا نُص عليها. لا يُرد مقابل الروابط التي سُلّمت وفق الطلب وما تزال منشورة.' },
        { title: '5. التزامات المشترين والناشرين', body: 'يلتزم المشتري بتقديم بيانات طلب دقيقة، بما فيها الصفحة المستهدفة والنص الرابط، ويقر بأن قرار النشر النهائي يعود إلى الناشر وأن Linkaza لا تضمن ترتيباً أو نتائج سيو محددة أو زيادة في الزيارات. ويلتزم الناشر بتمثيل بيانات موقعه وشروطه بدقة، ونشر المحتوى المعتمد في الوقت المناسب، والإبقاء على الرابط طوال الحد الأدنى للضمان المحدد في عرضه.' },
        { title: '6. القانون الحاكم', body: 'تخضع هذه الشروط وتُفسّر وفقاً لقوانين المملكة المتحدة، دون اعتبار لأحكام تنازع القوانين.' },
        { title: '7. التواصل', body: 'للاستفسارات المتعلقة بهذه الشروط، راسل legal@linkaza.com.' },
      ],
      bullets: ['شروط العرض تحدّد تفاصيل الطلب', 'لا ضمان لنتائج البحث', 'للاستفسارات: legal@linkaza.com'],
      cta: 'تواصل بشأن الشروط',
    },
    en: {
      eyebrow: 'Last updated: October 23, 2025',
      title: 'Terms and conditions',
      description: 'Terms governing the Linkaza website, platform and services, including accounts, placement orders, payments and buyer and publisher obligations.',
      intro: 'These terms govern access to the Linkaza website, platform and related services, owned and operated by Linkaza. By accessing or using the service, you agree to these terms. If you disagree with any part, you may not use the service.',
      sections: [
        { title: '1. Definitions', body: '“Service” means the Linkaza platform, website and related services. “User” means an individual or entity that creates an account and uses the service, including buyers and publishers. “Placement” means publication of content containing a backlink on a publisher’s website. “Content” includes articles, text, images and other materials provided or created in connection with a placement.' },
        { title: '2. Account registration and use', body: 'To use the service, you must register with accurate, current and complete information. You are responsible for safeguarding your password and for activity under your account. Notify us immediately when you become aware of a security breach or unauthorized account use. You must be at least 18 years old to use the service.' },
        { title: '3. The service', body: 'Linkaza provides a marketplace connecting buyers seeking backlinks with publishers offering placements on their websites. An optional content writing service may also be provided to facilitate placements. We reserve the right to refuse service to anyone for any reason at any time.' },
        { title: '4. Payments, credits and refunds', body: 'The service operates on a pay-as-you-go basis through an account wallet or payment per order. Publishers set placement prices, which are displayed in the marketplace. Refunds are considered case by case, including non-delivery, failure to meet agreed requirements, or removal during a specified guarantee period, such as 12 months where included in the offer. No refunds are issued for links delivered as ordered that remain live.' },
        { title: '5. Buyer and publisher obligations', body: 'Buyers must supply accurate order information, including target URLs and anchor text. Buyers acknowledge that publishers make the final publication decision and that Linkaza does not guarantee specific SEO results, rankings or traffic increases. Publishers must accurately represent their website metrics and guidelines, publish approved content in a timely manner and maintain the link for the minimum guarantee period specified in their listing.' },
        { title: '6. Governing law', body: 'These terms are governed and construed in accordance with the laws of the United Kingdom, without regard to conflict of law provisions.' },
        { title: '7. Contact', body: 'For questions about these terms, contact legal@linkaza.com.' },
      ],
      bullets: ['The offer defines order-specific terms', 'Search outcomes are not guaranteed', 'Questions: legal@linkaza.com'],
      cta: 'Contact us about these terms',
    },
  },
  'privacy-policy': {
    ar: {
      eyebrow: 'آخر تحديث: 23 أكتوبر 2025',
      title: 'سياسة الخصوصية وملفات الارتباط',
      description: 'تعرّف على طريقة جمع Linkaza للمعلومات واستخدامها ومشاركتها وحمايتها، وملفات تعريف الارتباط وحقوق البيانات ووسيلة التواصل.',
      intro: 'توضّح هذه السياسة كيفية جمع Linkaza للمعلومات واستخدامها والإفصاح عنها وحمايتها عند زيارة الموقع أو استخدام المنصة والخدمات. يُرجى قراءتها بعناية؛ باستخدام الخدمة، فإنك توافق على ممارسات البيانات الموضحة هنا.',
      sections: [
        { title: '1. المعلومات التي نجمعها', body: 'قد نجمع معلومات شخصية مثل الاسم والبريد الإلكتروني واسم الشركة ومعلومات الدفع، ومعلومات تجمعها الخوادم تلقائياً مثل عنوان IP ونوع المتصفح ونظام التشغيل. نحتفظ بمعلومات مالية محدودة جداً، بينما تُخزّن بقية المعلومات المالية لدى معالج الدفع.' },
        { title: '2. كيف نستخدم المعلومات', body: 'قد نستخدم المعلومات لإنشاء حسابك وإدارته، ومعالجة المعاملات وتقديم الخدمات المطلوبة، والتواصل بشأن الحساب أو الطلبات، وتحليل الاستخدام لتحسين التجربة، ومنع المعاملات الاحتيالية ومراقبة السرقة.' },
        { title: '3. مشاركة المعلومات', body: 'لا نبيع أو نتاجر أو نؤجّر معلوماتك التعريفية الشخصية. قد نشارك المعلومات للاستجابة لإجراءات قانونية عندما نعتقد أن الإفصاح ضروري، أو مع مزوّدي خدمات يعملون نيابة عنا، مثل مزوّدي معالجة الدفع والاستضافة.' },
        { title: '4. ملفات تعريف الارتباط', body: 'قد تستخدم الخدمة ملفات تعريف الارتباط وإشارات الويب وبكسلات التتبّع وتقنيات مشابهة لتخصيص التجربة وتحسينها. يمكنك إزالة ملفات الارتباط أو رفضها عبر إعدادات المتصفح، لكن ذلك قد يؤثر في توفر بعض وظائف الخدمة.' },
        { title: '5. أمان البيانات', body: 'نستخدم إجراءات إدارية وتقنية ومادية للمساعدة على حماية المعلومات الشخصية. مع اتخاذ خطوات معقولة للحماية، لا توجد إجراءات أمان كاملة أو منيعة تماماً.' },
        { title: '6. حقوق حماية البيانات', body: 'بحسب موقعك والقوانين المطبقة، قد يحق لك الوصول إلى بياناتك الشخصية وطلب نسخة منها، وتصحيح المعلومات غير الدقيقة، وطلب محو البيانات أو تقييد معالجتها.' },
        { title: '7. تحديثات هذه السياسة', body: 'قد نحدّث السياسة من وقت لآخر. تُنشر التغييرات على هذه الصفحة مع تحديث تاريخ آخر مراجعة.' },
        { title: '8. التواصل', body: 'للأسئلة أو الملاحظات أو طلبات الخصوصية، راسل legal@linkaza.com.' },
      ],
      bullets: ['معلومات الحساب والطلبات', 'حقوق تختلف حسب القانون المطبق', 'للتواصل: legal@linkaza.com'],
      cta: 'تواصل بشأن الخصوصية',
    },
    en: {
      eyebrow: 'Last updated: October 23, 2025',
      title: 'Privacy & cookie policy',
      description: 'Learn how Linkaza collects, uses, shares and protects information, and read about cookies, data protection rights and privacy contact details.',
      intro: 'This policy explains how Linkaza collects, uses, discloses and safeguards information when you visit our website or use the platform and services. Please read it carefully. By using the service, you consent to the data practices described here.',
      sections: [
        { title: '1. Information we collect', body: 'We may collect personal information such as your name, email, company name and payment information, as well as server-collected details such as IP address, browser type and operating system. We store very limited financial information; other financial information is stored by our payment processor.' },
        { title: '2. How we use information', body: 'We may use information to create and manage your account, process transactions and deliver requested services, contact you about accounts or orders, analyze usage to improve the experience, and prevent fraudulent transactions and monitor against theft.' },
        { title: '3. Sharing information', body: 'We do not sell, trade or rent personally identifiable information. Information may be shared where we believe disclosure is necessary to respond to legal process, or with service providers working on our behalf, such as payment processors and hosting providers.' },
        { title: '4. Cookies', body: 'The service may use cookies, web beacons, tracking pixels and similar technologies to customize and improve the experience. You can remove or reject cookies through browser settings, but this may affect the availability and functionality of parts of the service.' },
        { title: '5. Data security', body: 'We use administrative, technical and physical measures to help protect personal information. Although we take reasonable steps to secure information, no security measures are perfect or impenetrable.' },
        { title: '6. Data protection rights', body: 'Depending on your location and applicable law, you may have rights to access and obtain copies of personal data, correct inaccurate information, request erasure or restrict processing.' },
        { title: '7. Policy updates', body: 'We may update this policy from time to time. Changes will be posted on this page with an updated last-reviewed date.' },
        { title: '8. Contact', body: 'For privacy questions, comments or requests, contact legal@linkaza.com.' },
      ],
      bullets: ['Account and order information', 'Rights depend on applicable law', 'Contact: legal@linkaza.com'],
      cta: 'Contact us about privacy',
    },
  },
};
