import type { Locale } from './site';

export type PageContent = {
  eyebrow: string;
  title: string;
  description: string;
  intro: string;
  sections: { title: string; body: string }[];
  bullets: string[];
  cta: string;
};

export const pages: Record<string, Record<Locale, PageContent>> = {
  marketplace: {
    ar: {
      eyebrow: 'سوق الباك لينك',
      title: 'الموقع المناسب. للرابط المناسب.',
      description: 'اكتشف سوق Linkaza لشراء الباك لينك والجيست بوست. قارن مواقع النشر حسب التخصص والجمهور وشروط العرض، ثم اختر ما يناسب حملتك.',
      intro: 'قرار نشر أفضل يبدأ بمعلومات أوضح. قارن الفرص، افهم جمهور كل موقع، واختر مساحة تضيف معنى لظهور علامتك.',
      sections: [
        { title: 'ابدأ من جمهورك', body: 'حدّد لغة حملتك والسوق الذي تستهدفه، ثم ابحث عن مواقع ترتبط بموضوعك. الموقع المتخصص الذي يقرأه عميلك المحتمل قد يكون أنسب من موقع عام بمؤشر أعلى.' },
        { title: 'اقرأ ما وراء المؤشرات', body: 'راجع اتجاه الزيارات وأمثلة المقالات والصفحات التي تجذب الجمهور. استخدم مؤشرات قوة النطاق للمقارنة، مع الانتباه إلى مصدر كل رقم وتاريخ تحديثه.' },
        { title: 'افهم العرض قبل الطلب', body: 'تحقّق من سعر النشر، وما إذا كانت الكتابة مشمولة، ونوع الرابط ومدة النشر وشروط الناشر. تجد العروض المتاحة وتفاصيل تنفيذها داخل حسابك.' },
      ],
      bullets: ['تخصص يرتبط بمحتواك', 'جمهور يناسب سوقك', 'شروط واضحة قبل الطلب'],
      cta: 'استكشف السوق',
    },
    en: {
      eyebrow: 'The backlink marketplace',
      title: 'The right website. The right connection.',
      description: 'Explore the Linkaza backlink and guest post marketplace. Compare publisher relevance, audiences and placement terms before choosing your next opportunity.',
      intro: 'A better placement starts with a clearer picture. Understand the publisher, compare the offer and put your brand in a relevant conversation.',
      sections: [
        { title: 'Start with your audience', body: 'Choose your target language and market, then look for publishers that cover your subject. A focused publication your customers actually read can be a better fit than a general website with a higher score.' },
        { title: 'Look beyond the headline metric', body: 'Review traffic trends, recent articles and the pages attracting readers. Use domain metrics as comparison signals, and check the source and freshness of the available data.' },
        { title: 'Know what you are ordering', body: 'Check the placement price, writing requirements, link attributes, publication timeline and publisher terms. Current opportunities and order details are available in your account.' },
      ],
      bullets: ['Relevant subject coverage', 'An audience that fits', 'Placement terms you can review'],
      cta: 'Explore the marketplace',
    },
  },
  pricing: {
    ar: {
      eyebrow: 'التكلفة والميزانية',
      title: 'اختر الفرصة. وحدّد استثمارك.',
      description: 'تعرّف على طريقة تسعير الباك لينك والجيست بوست في Linkaza: الدفع حسب الطلب، وأسعار الناشرين، وتكلفة المحتوى وشروط النشر.',
      intro: 'تختلف تكلفة الباك لينك باختلاف الموقع والمحتوى وشروط النشر. ابنِ ميزانيتك على عروض محددة تعرف تفاصيلها.',
      sections: [
        { title: 'الدفع حسب الطلب', body: 'تعمل Linkaza بنظام الدفع بحسب الاستخدام. يحدّد الناشر سعر عرضه، ويمكنك مراجعة السعر داخل السوق قبل الشراء، مع الدفع لكل طلب أو من رصيد الحساب بحسب الخيارات المتاحة.' },
        { title: 'قارن التكلفة الكاملة', body: 'تحقّق مما يشمله العرض: النشر فقط أم كتابة المقال أيضاً، ومتطلبات الصور أو المراجعة أو الإضافات. قارن عروضاً متقاربة في الجمهور والتخصص حتى يكون فرق السعر مفهوماً.' },
        { title: 'شروط النشر جزء من القيمة', body: 'راجع مدة بقاء المقال والرابط وأي ضمان محدد في العرض. تُدرس طلبات الاسترداد وفق حالة الطلب والشروط المتفق عليها؛ لا توجد مدة ضمان موحّدة تُفترض لكل المواقع.' },
      ],
      bullets: ['سعر الناشر قبل الشراء', 'ميزانية تختارها لكل حملة', 'تفاصيل العرض هي مرجعك'],
      cta: 'شاهد العروض المتاحة',
    },
    en: {
      eyebrow: 'Pricing & budgets',
      title: 'Choose the opportunity. Own the budget.',
      description: 'Understand Linkaza backlink and guest post pricing: pay per order, compare publisher offers, and check content costs and placement terms before buying.',
      intro: 'Every publisher offer is different. Build your budget around the audience, content and publication terms you actually need.',
      sections: [
        { title: 'Pay as you go', body: 'Linkaza operates on a pay-as-you-go basis. Publishers set their placement prices, which you can review in the marketplace before purchase. Available payment options include individual orders or your account balance.' },
        { title: 'Compare the complete cost', body: 'Check whether an offer covers publication alone or includes writing, and confirm any image, revision or additional-content requirements. Compare publishers with similar audiences and subject coverage.' },
        { title: 'Read the placement terms', body: 'Check how long the article and link must remain live and any guarantee included in the listing. Refund requests are assessed against the order and its agreed terms; do not assume one guarantee period applies to every publisher.' },
      ],
      bullets: ['Publisher prices before purchase', 'A budget for each campaign', 'Offer-specific publication terms'],
      cta: 'View available offers',
    },
  },
  solutions: {
    ar: {
      eyebrow: 'حلول Linkaza',
      title: 'طريقة عملك. نقطة البداية.',
      description: 'حلول بناء الروابط للوكالات ومستشاري السيو والشركات والناشرين. اختر المسار المناسب لحملات الباك لينك والجيست بوست مع Linkaza.',
      intro: 'تختلف الحملات، ويبقى القرار الجيد مبنياً على جمهور مناسب ومحتوى مفيد وتفاصيل واضحة.',
      sections: [
        { title: 'للوكالات والمستشارين', body: 'ابدأ بمعايير اختيار ثابتة لكل عميل: القطاع، اللغة، الجمهور والميزانية. استخدمها لبناء قائمة نشر يسهل شرحها ومراجعتها، مع توثيق سبب اختيار كل موقع.' },
        { title: 'للشركات والمتاجر', body: 'اربط كل فرصة بصفحة ذات قيمة: دليل متخصص، دراسة أصلية، فئة منتجات أو خدمة واضحة. فكّر فيما سيجده الزائر بعد النقر، وكيف ستقيس اهتمامه بعلامتك.' },
        { title: 'للناشرين', body: 'حوّل خبرتك التحريرية وجمهورك إلى عرض واضح للمعلنين. اشرح تخصص موقعك وشروط قبول المحتوى والسعر والمدة المتوقعة، مع الحفاظ على تجربة قرّائك.' },
      ],
      bullets: ['الوكالات ومستشارو السيو', 'الشركات والمتاجر الإلكترونية', 'المواقع والناشرون'],
      cta: 'اعثر على فرصتك التالية',
    },
    en: {
      eyebrow: 'Built around your work',
      title: 'Different teams. Better connections.',
      description: 'Explore Linkaza link building solutions for agencies, SEO consultants, businesses and publishers, with relevant audiences and clear placement decisions.',
      intro: 'Your workflow may differ. The essentials stay the same: a relevant audience, useful content and an offer you understand.',
      sections: [
        { title: 'For agencies and consultants', body: 'Set selection criteria for every client: industry, language, audience and budget. Use them to build a publisher shortlist you can explain, review and connect to the campaign brief.' },
        { title: 'For businesses and stores', body: 'Give every placement a useful destination: an expert guide, original research, a product category or a clear service page. Consider the experience after the click and how you will measure interest.' },
        { title: 'For publishers', body: 'Turn your editorial expertise and audience into a clear offer. Describe your subject coverage, content requirements, price and expected timeline while protecting the experience your readers value.' },
      ],
      bullets: ['Agencies and SEO consultants', 'Businesses and ecommerce teams', 'Independent publishers'],
      cta: 'Find your next opportunity',
    },
  },
  agencies: {
    ar: {
      eyebrow: 'للوكالات',
      title: 'حملات يمكن أن تقف وراءها.',
      description: 'خطّط لحملات باك لينك وجيست بوست لعملاء وكالتك مع Linkaza. قارن الناشرين، اضبط متطلبات المحتوى، ووثّق قرارات النشر.',
      intro: 'كل عميل له سياقه. اجمع اختيارات النشر حول خطة واضحة يمكن لفريقك تنفيذها ولعميلك فهمها.',
      sections: [
        { title: 'معايير خاصة بكل عميل', body: 'أنشئ موجزاً يحدد السوق واللغة والصفحات المستهدفة والناشرين المستبعدين. اجعل الصلة بالموضوع معياراً أساسياً، ثم قارن البيانات والتكلفة وشروط النشر.' },
        { title: 'موافقة تستند إلى تفاصيل', body: 'شارك سبب ترشيح الموقع وزاوية المقال والميزانية مع العميل قبل التنفيذ. وثّق النص الرابط ومتطلبات العلامة، حتى يعرف الكاتب والناشر ما الذي تم اعتماده.' },
        { title: 'تقرير يشرح العمل', body: 'اجمع روابط المقالات المنشورة وتواريخها وصفحاتها المستهدفة. افصل بين تنفيذ الطلب ومؤشرات الأداء، وقدّم سياقاً لتغيّر الزيارات أو التحويلات بدلاً من نسبته تلقائياً إلى رابط واحد.' },
      ],
      bullets: ['اختيارات مرتبطة بموجز العميل', 'محتوى ومتطلبات موثّقة', 'تقارير مفهومة لأصحاب القرار'],
      cta: 'خطّط لحملة عميلك',
    },
    en: {
      eyebrow: 'For agencies',
      title: 'Campaigns you can stand behind.',
      description: 'Plan backlink and guest post campaigns for agency clients with Linkaza. Compare publishers, define content requirements and document placement decisions.',
      intro: 'Each client brings a different context. Build a publishing plan your team can execute and your client can understand.',
      sections: [
        { title: 'Criteria for every account', body: 'Define the target market, language, destination pages and excluded publishers. Make topical relevance a first requirement, then compare available data, cost and publication terms.' },
        { title: 'Approvals with context', body: 'Share your publisher rationale, proposed article angle and budget before ordering. Record approved anchor text and brand requirements so the writer and publisher work from the same brief.' },
        { title: 'Reporting that explains the work', body: 'Keep the published URLs, dates and destination pages together. Separate delivery from performance, and give traffic or conversion changes their proper context instead of attributing them to one link.' },
      ],
      bullets: ['Client-specific publisher criteria', 'Documented content requirements', 'Clear stakeholder reporting'],
      cta: 'Plan your next client campaign',
    },
  },
  consultants: {
    ar: {
      eyebrow: 'لمستشاري السيو',
      title: 'خبرتك في الاختيار تصنع الفرق.',
      description: 'استخدم Linkaza لاختيار فرص باك لينك وجيست بوست تناسب عملاءك. إرشادات للمقارنة والتخطيط ومراجعة النشر لمستشاري تحسين محركات البحث.',
      intro: 'وفّر تركيزك لما يحتاج إلى خبرتك: فهم السوق، وتقييم الموقع، واختيار قصة تستحق النشر.',
      sections: [
        { title: 'قائمة أقصر وأكثر صلة', body: 'حدّد أسباب الاستبعاد مبكراً: لغة لا تناسب الحملة، محتوى بعيد عن المجال، أو بيانات يصعب تفسيرها. ركّز وقت التقييم على المواقع التي تحقق المعايير الأساسية.' },
        { title: 'التوصية تبدأ من التحليل', body: 'راجع الصفحة المستهدفة قبل البحث عن روابط لها. إذا كانت لا تجيب عن حاجة الزائر أو يصعب استخدامها، فقد يكون تحسينها هو الخطوة الأجدى قبل الاستثمار في النشر.' },
        { title: 'مراجعة منظمة بعد النشر', body: 'قارن المقال المنشور بالموجز، وافحص الرابط ووجهته وخصائصه. احتفظ بتاريخ التنفيذ وملاحظاتك لتبني عليها قرارات الحملة التالية.' },
      ],
      bullets: ['معايير تقييم قابلة للتكرار', 'قرارات تخدم خطة السيو', 'تفاصيل يسهل الرجوع إليها'],
      cta: 'ابدأ قائمة النشر الخاصة بك',
    },
    en: {
      eyebrow: 'For SEO consultants',
      title: 'Your judgment makes the difference.',
      description: 'Use Linkaza to find backlink and guest post opportunities for your clients, with a practical approach to publisher selection, content briefs and delivery reviews.',
      intro: 'Keep your attention on the work that needs your expertise: understanding the market, assessing a publisher and choosing a useful story.',
      sections: [
        { title: 'A tighter, more relevant shortlist', body: 'Define exclusions early: the wrong language, unrelated subject coverage or data that needs more explanation. Spend your review time on publishers that meet the basic campaign requirements.' },
        { title: 'Advice starts with analysis', body: 'Review the destination page before finding links to it. If it does not answer a visitor’s need or is difficult to use, improving that page may be the better first investment.' },
        { title: 'A repeatable delivery review', body: 'Compare the live article with the brief, then check the link, destination and attributes. Keep the delivery date and your observations so the next campaign benefits from what you learned.' },
      ],
      bullets: ['Repeatable publisher evaluation', 'Decisions connected to SEO strategy', 'A clear record of each placement'],
      cta: 'Build your publisher shortlist',
    },
  },
  businesses: {
    ar: {
      eyebrow: 'للشركات والمتاجر',
      title: 'دع علامتك تدخل الحديث المناسب.',
      description: 'اكتشف فرص نشر وباك لينك للشركات والمتاجر مع Linkaza. اختر جمهوراً يناسب نشاطك ومحتوى يشرح قيمتك وصفحات تستقبل الزيارات بوضوح.',
      intro: 'اختر مساحات يتابعها جمهورك، وقدّم محتوى يساعده على فهم ما تعرفه وما تقدّمه.',
      sections: [
        { title: 'انطلق من سؤال العميل', body: 'ما الذي يسأل عنه جمهورك قبل الشراء؟ اجعل المقال يجيب عن سؤال حقيقي بمثال أو مقارنة أو خبرة عملية، ثم اربط بمصدر مفيد داخل موقعك.' },
        { title: 'اختر وجهة جاهزة للزائر', body: 'تأكد أن صفحة الوصول سريعة وواضحة وتعمل على الهاتف. وجّه القارئ إلى الصفحة الأكثر ارتباطاً بسياق المقال، بدلاً من إرسال جميع الروابط إلى الصفحة الرئيسية.' },
        { title: 'قِس ما يهم النشاط', body: 'تابع زيارات الإحالة والتفاعل والاستفسارات المرتبطة بها عندما تكون أدوات القياس متاحة. اقرأ أداء البحث ضمن الخطة التسويقية كاملة، مع مراعاة الموسم والتغييرات الأخرى في موقعك.' },
      ],
      bullets: ['وصول إلى جمهور ذي صلة', 'قصص تُظهر خبرتك', 'أهداف مرتبطة بنشاطك'],
      cta: 'اكتشف فرص علامتك',
    },
    en: {
      eyebrow: 'For businesses',
      title: 'Put your brand in the right conversation.',
      description: 'Discover publishing and backlink opportunities for businesses with Linkaza. Connect relevant audiences with useful content and a clear destination on your website.',
      intro: 'Choose publications your audience cares about, then give their readers a useful reason to discover your brand.',
      sections: [
        { title: 'Start with a customer question', body: 'What does your audience need to understand before buying? Answer a real question with a practical example, comparison or experience, and point to a genuinely useful resource on your website.' },
        { title: 'Make the destination ready', body: 'Check that your landing page is fast, clear and usable on mobile. Link to the page that best continues the article’s subject instead of sending every visitor to the homepage.' },
        { title: 'Measure what matters to the business', body: 'Where your analytics allow it, review referral visits, engagement and enquiries. Interpret search performance in the context of your wider marketing work, seasonality and other website changes.' },
      ],
      bullets: ['A relevant readership', 'Content that demonstrates expertise', 'Goals connected to your business'],
      cta: 'Find opportunities for your brand',
    },
  },
  publishers: {
    ar: {
      eyebrow: 'للناشرين',
      title: 'جمهورك قيمة. قدّمها بوضوح.',
      description: 'انضم إلى Linkaza كناشر واعرض فرص النشر على موقعك. وضّح تخصصك وشروط المقالات والأسعار ومتطلبات المحتوى للمعلنين المناسبين.',
      intro: 'افتح باب التعاون مع علامات ترتبط باهتمامات قرّائك، مع شروط نشر تحافظ على هويتك التحريرية.',
      sections: [
        { title: 'عرّف بموقعك بدقة', body: 'اذكر لغة الموقع وتخصصه والجمهور الذي يخدمه. قدّم بيانات يمكنك إثباتها وأمثلة حديثة من محتواك، وميّز بوضوح بين الأرقام المقاسة والتقديرات الخارجية.' },
        { title: 'ضع شروطك قبل استقبال الطلبات', body: 'حدّد الموضوعات المقبولة ومتطلبات المقال والروابط والسعر ومدة التنفيذ المتوقعة. اشرح مدة بقاء النشر وأي شروط للمراجعة، حتى يبدأ التعاون بتوقعات متفقة.' },
        { title: 'حافظ على تجربة القارئ', body: 'راجع المحتوى لتتأكد من أصالته وصلته بالموقع. وضّح طبيعة التعاون المدفوع واستخدم خصائص الرابط المناسبة؛ القرار التحريري النهائي بالنشر يعود إليك.' },
      ],
      bullets: ['تخصص وجمهور واضحان', 'شروط نشر تحددها مسبقاً', 'محتوى يناسب قرّاءك'],
      cta: 'انضم كناشر',
    },
    en: {
      eyebrow: 'For publishers',
      title: 'Your audience has value. Make it clear.',
      description: 'Join Linkaza as a publisher and present your website’s placement opportunities, editorial requirements and pricing to relevant advertisers.',
      intro: 'Work with brands that fit your readership while keeping the editorial standards that make your publication yours.',
      sections: [
        { title: 'Represent your publication accurately', body: 'Describe your language, subject coverage and audience. Provide evidence for the data you share and recent examples of your content. Distinguish measured figures from third-party estimates.' },
        { title: 'Set expectations before an order', body: 'Specify accepted subjects, article and link requirements, price and expected delivery time. Explain publication duration and revision terms so both sides understand the offer.' },
        { title: 'Protect the reader experience', body: 'Review content for originality and relevance. Disclose paid relationships and use appropriate link attributes. As the publisher, you retain the final editorial decision about publication.' },
      ],
      bullets: ['A clearly described audience', 'Your publication requirements', 'Content that belongs on your website'],
      cta: 'Join as a publisher',
    },
  },
  'content-service': {
    ar: {
      eyebrow: 'كتابة المحتوى',
      title: 'مقال يستحق القراءة. قبل الرابط.',
      description: 'خطّط لمحتوى عربي وإنكليزي مناسب للجيست بوست وبناء الروابط. تعرّف على موجز المقال ومعايير التحرير ومتطلبات خدمة المحتوى في Linkaza.',
      intro: 'الرابط جزء من القصة. والمحتوى الجيد يمنح القارئ سبباً ليتابعها.',
      sections: [
        { title: 'موجز واضح يصنع مقالاً أفضل', body: 'حدّد القارئ المستهدف، والسؤال الذي يجيب عنه المقال، وزاويته، ومصادره. أضف الصفحة المستهدفة ومتطلبات الناشر ونبرة علامتك قبل الاتفاق على الكتابة.' },
        { title: 'لغة تناسب الجمهور', body: 'المحتوى العربي يحتاج صياغة أصلية وسياقاً محلياً، والنسخة الإنكليزية تحتاج أمثلتها ومصطلحاتها المناسبة. تجنّب الترجمة الحرفية وتكرار الكلمات المفتاحية على حساب المعنى.' },
        { title: 'مراجعة قبل النشر', body: 'راجع صحة المعلومات وحقوق الصور والروابط والأصالة، ثم طابق النص مع متطلبات الناشر. توفّر الكتابة وتكلفتها ونطاق التعديلات تُحدّد ضمن العرض أو بعد التواصل مع الفريق.' },
      ],
      bullets: ['زاوية تخدم القارئ', 'صياغة مناسبة للغة والسوق', 'متطلبات تحرير واضحة'],
      cta: 'ناقش متطلبات المحتوى',
    },
    en: {
      eyebrow: 'Content writing',
      title: 'An article worth reading. A reason to click.',
      description: 'Plan useful Arabic and English guest post content with Linkaza. Learn what to include in your brief, editorial review and content service requirements.',
      intro: 'A link is part of the story. Good content gives the reader a reason to follow it.',
      sections: [
        { title: 'A clear brief comes first', body: 'Define the reader, the question you will answer, your angle and supporting sources. Include the destination page, publisher requirements and brand voice before agreeing on writing.' },
        { title: 'Write for the language and market', body: 'Arabic content needs natural phrasing and appropriate local context. English content needs its own examples and vocabulary. Literal translation and repeated keywords should never get in the way of meaning.' },
        { title: 'Review before publication', body: 'Check facts, image rights, links and originality, then compare the draft with the publisher’s requirements. Writing availability, pricing and revision scope depend on the offer or a discussion with the team.' },
      ],
      bullets: ['A reader-first angle', 'Language that fits the market', 'Clear editorial requirements'],
      cta: 'Discuss your content brief',
    },
  },
  'strategy-builder': {
    ar: {
      eyebrow: 'تخطيط الحملات',
      title: 'لكل رابط مكان في الخطة.',
      description: 'ابنِ خطة باك لينك تبدأ من أهدافك وصفحاتك وجمهورك. إطار عملي لتحديد أولويات النشر والميزانية والمراجعة مع Linkaza.',
      intro: 'اجعل اختيار الناشر نتيجة لخطة واضحة: أين تريد الظهور، ولمن، وبأي محتوى؟',
      sections: [
        { title: 'اختر صفحات تستحق الأولوية', body: 'ابدأ بصفحات مكتملة وتخدم هدفاً واضحاً. دوّن لكل صفحة الجمهور والموضوع والنتيجة التي تريد قياسها، وحدّد ما يحتاج تحسيناً داخل موقعك قبل النشر الخارجي.' },
        { title: 'حلّل الفجوة بوعي', body: 'افحص أين يظهر منافسوك وكيف يقدّمون خبرتهم. ابحث عن موضوعات أو شرائح جمهور لم تخدمها بعد، ولا تعتبر كل موقع يربط بمنافسك اختياراً مناسباً لك تلقائياً.' },
        { title: 'وزّع التنفيذ وراجع القرار', body: 'ضع قائمة أولية بالناشرين وزوايا المقالات والتكلفة، ثم نفّذ على مراحل تناسب قدرتك على الإنتاج والمراجعة. استخدم النتائج لتعديل الاختيارات، وليس لافتراض عدد سحري من الروابط.' },
      ],
      bullets: ['هدف وصفحة لكل فرصة', 'فجوات مرتبطة بجمهورك', 'ميزانية قابلة للمراجعة'],
      cta: 'ابدأ تخطيط حملتك',
    },
    en: {
      eyebrow: 'Campaign strategy',
      title: 'Give every link a place in the plan.',
      description: 'Build a backlink plan around your goals, destination pages and audience. A practical framework for placement priorities, budgets and campaign reviews.',
      intro: 'Let a clear strategy guide publisher selection: where should you appear, who should you reach and what should you say?',
      sections: [
        { title: 'Prioritize pages with a purpose', body: 'Start with complete pages that serve a clear goal. Record the audience, subject and intended outcome for each one. Identify on-site improvements needed before investing in outside placements.' },
        { title: 'Interpret the competitor gap', body: 'Look at where competitors appear and how they share expertise. Find under-served topics or audiences, and assess each opportunity independently instead of copying every referring domain.' },
        { title: 'Stage the work and review decisions', body: 'Map publishers, article angles and costs, then publish at a pace your team can brief and review properly. Let the evidence improve your next choices rather than aiming for a supposedly ideal link count.' },
      ],
      bullets: ['A goal for every destination', 'Audience-led opportunity analysis', 'A budget you can review'],
      cta: 'Start planning your campaign',
    },
  },
  analytics: {
    ar: {
      eyebrow: 'القياس والمتابعة',
      title: 'من رابط منشور إلى صورة أوضح.',
      description: 'تعرّف على كيفية متابعة حملات الباك لينك: فحص النشر، زيارات الإحالة، أداء صفحاتك في البحث وقراءة النتائج ضمن سياقها الصحيح.',
      intro: 'اعرف ما تم تنفيذه، وما تغيّر بعده، وما يمكنك الاستنتاج منه فعلاً.',
      sections: [
        { title: 'ابدأ بالتحقق من التسليم', body: 'افحص عنوان المقال ومحتواه والرابط المستهدف والنص الرابط وخصائصه. احتفظ بالرابط المباشر وتاريخ النشر وشروط الطلب لتسهيل أي مراجعة لاحقة.' },
        { title: 'راقب أكثر من إشارة', body: 'استخدم أدوات تحليلات موقعك لقراءة زيارات الإحالة والتفاعل والتحويلات، وSearch Console لمتابعة النقرات والظهور والصفحات والاستعلامات. هذه إشارات مختلفة، ولكل منها حدودها.' },
        { title: 'اقرأ التغيير في سياقه', body: 'دوّن تعديلات المحتوى والموقع والتغيّرات الموسمية خلال فترة القياس. تزامن تحسّن الترتيب مع حملة نشر لا يثبت وحده أن الحملة سبب التحسّن، ولا يضمن تكرار النتيجة.' },
      ],
      bullets: ['توثيق النشر الفعلي', 'قياس الزيارات والتفاعل', 'قراءة واقعية للنتائج'],
      cta: 'ناقش قياس حملتك',
    },
    en: {
      eyebrow: 'Measurement & reporting',
      title: 'From a published link to a clearer picture.',
      description: 'Learn how to review backlink campaigns: verify published placements, measure referral traffic and understand search performance in its wider context.',
      intro: 'Know what was delivered, what changed afterwards and what the evidence actually lets you conclude.',
      sections: [
        { title: 'Verify the placement first', body: 'Review the article title, content, destination, anchor text and link attributes. Keep the published URL, date and order terms together to make later checks straightforward.' },
        { title: 'Read more than one signal', body: 'Use your own analytics for referral visits, engagement and conversions. Use Search Console for search clicks, impressions, pages and queries. These answer different questions and each has limitations.' },
        { title: 'Give changes their context', body: 'Record content updates, technical changes and seasonal factors during the reporting period. A ranking improvement after publication does not, by itself, establish that the placement caused it or that it will happen again.' },
      ],
      bullets: ['Documented publication checks', 'Traffic and engagement measures', 'Evidence with proper context'],
      cta: 'Discuss your reporting needs',
    },
  },
  about: {
    ar: {
      eyebrow: 'عن Linkaza',
      title: 'روابط أفضل تبدأ بقرارات أوضح.',
      description: 'Linkaza منصة تجمع المشترين والناشرين لفرص الباك لينك والجيست بوست. تعرّف على رؤيتنا للجودة والمحتوى وتجربة النشر بالعربية والإنكليزية.',
      intro: 'نقرّب المسافة بين علامة لديها ما تقوله، وناشر يملك الجمهور المناسب لسماعها.',
      sections: [
        { title: 'مساحة تجمع طرفَي النشر', body: 'تربط Linkaza المشترين الباحثين عن فرص باك لينك وجيست بوست بالناشرين الذين يعرضون مواقعهم. يختار المشتري العرض الذي يناسبه، ويحتفظ الناشر بمعاييره وقراره التحريري.' },
        { title: 'العربية جزء من التجربة', body: 'السوق العربي يحتاج لغة واضحة وفهماً لاختلاف الجمهور بين الدول والقطاعات. لذلك نقدّم تجربة عربية وإنكليزية تساعدك على فهم الخيارات والتفاصيل بلغتك.' },
        { title: 'الجودة تُشرح ولا تُختصر برقم', body: 'نؤمن بأن التخصص والجمهور والمحتوى وشروط النشر يجب أن تبقى في قلب القرار. قوة النطاق مفيدة للمقارنة، لكنها لا تغني عن قراءة الموقع ومعرفة ما ستشتريه.' },
      ],
      bullets: ['صلة حقيقية بالموضوع', 'تجربة عربية وإنكليزية', 'تفاصيل تساعد على الاختيار'],
      cta: 'تعرّف على السوق',
    },
    en: {
      eyebrow: 'About Linkaza',
      title: 'Better connections start with clearer choices.',
      description: 'Linkaza connects buyers and publishers for backlink and guest post opportunities. Learn about our approach to relevance, content and Arabic-English publishing.',
      intro: 'We bring together brands with something useful to say and publishers with the audience to hear it.',
      sections: [
        { title: 'A meeting point for publishing', body: 'Linkaza connects buyers looking for backlink and guest post opportunities with publishers offering placements. Buyers choose the offers that fit their plans; publishers retain their editorial standards and final publication decisions.' },
        { title: 'Arabic belongs at the center', body: 'Arabic-speaking markets deserve clear language and an understanding of how audiences differ across countries and industries. Our Arabic and English experience helps you evaluate the details in your own language.' },
        { title: 'Quality needs an explanation', body: 'Relevance, readership, content and publication terms should sit at the center of a decision. Domain metrics are useful comparison signals, but they cannot replace reviewing a website and understanding the offer.' },
      ],
      bullets: ['Topical relevance', 'An Arabic and English experience', 'Details that support better decisions'],
      cta: 'Get to know the marketplace',
    },
  },
  blog: {
    ar: {
      eyebrow: 'دليل Linkaza',
      title: 'اعرف أكثر. اختر أفضل.',
      description: 'أدلة عملية في الباك لينك والجيست بوست: تقييم جودة المواقع، كتابة موجز النشر وتخطيط ميزانية بناء الروابط، بالعربية والإنكليزية.',
      intro: 'معرفة عملية تساعدك على تقييم الفرص، وطرح الأسئلة الصحيحة، وبناء حملات أكثر وضوحاً.',
      sections: [
        { title: 'جودة الموقع', body: 'تعلّم كيف تفحص الصلة بالموضوع واتجاه الزيارات وأسلوب النشر، وكيف تضع مؤشرات قوة النطاق في حجمها الصحيح عند المقارنة.' },
        { title: 'المحتوى والجيست بوست', body: 'من اختيار زاوية المقال إلى مراجعة النسخة المنشورة: خطوات تساعدك على إعداد محتوى يناسب القارئ والناشر والصفحة التي تربط بها.' },
        { title: 'التخطيط والميزانية', body: 'حدّد ما يدخل في تكلفة الحملة، وما يستحق الأولوية، وما تحتاج إلى قياسه قبل توسيع النشر. قرار واعٍ أفضل من شراء عدد غير مدروس من الروابط.' },
      ],
      bullets: ['أدلة عملية باللغة العربية', 'خطوات يمكنك تطبيقها', 'مصادر مباشرة عند الحاجة'],
      cta: 'اكتشف فرص النشر',
    },
    en: {
      eyebrow: 'The Linkaza journal',
      title: 'Know more. Choose better.',
      description: 'Practical backlink and guest posting guides in English and Arabic. Learn to evaluate publishers, prepare content briefs and plan a link building budget.',
      intro: 'Practical knowledge for evaluating opportunities, asking better questions and making clearer campaign decisions.',
      sections: [
        { title: 'Publisher quality', body: 'Learn to assess subject relevance, traffic trends and publishing patterns, and put third-party domain scores in their proper place when comparing websites.' },
        { title: 'Content and guest posting', body: 'From choosing an article angle to reviewing the live placement, prepare content that fits the reader, the publication and the destination you are linking to.' },
        { title: 'Planning and budgets', body: 'Understand the full campaign cost, decide what deserves priority and define your measures before expanding. A considered selection is more useful than an arbitrary target number of links.' },
      ],
      bullets: ['Practical Arabic and English guides', 'Steps you can apply', 'Direct sources where they matter'],
      cta: 'Explore publishing opportunities',
    },
  },
  affiliate: {
    ar: {
      eyebrow: 'شراكات وإحالات',
      title: 'توصية تبدأ بفهم جمهورك.',
      description: 'تعرّف على برنامج شراكات Linkaza والإحالات. ناقش ملاءمة جمهورك وشروط العمولة والتتبّع والدفع مع الفريق قبل بدء التعاون.',
      intro: 'إذا كان جمهورك يبحث عن فرص نشر وباك لينك، لنتحدث عن شراكة تقدّم له قيمة واضحة.',
      sections: [
        { title: 'شاركنا طبيعة جمهورك', body: 'عرّفنا بموقعك أو قناتك ونوع المحتوى الذي تقدّمه والأسواق التي تصل إليها. يساعد هذا السياق على تقييم ملاءمة التعاون وطريقة تقديم Linkaza لجمهورك.' },
        { title: 'اتفق على التفاصيل أولاً', body: 'ناقش معدل العمولة والطلبات المؤهلة وآلية الإسناد وشروط الدفع مباشرة مع الفريق. تُحدّد شروط الشراكة خلال التقديم، فلا تفترض نسبة أو استحقاقاً قبل الاتفاق.' },
        { title: 'توصية واضحة وشفافة', body: 'اشرح الخدمة كما هي وافصح لجمهورك عن علاقتك التجارية. استخدم أمثلة مفيدة وتجنّب الوعود بترتيب أو نتائج غير مضمونة.' },
      ],
      bullets: ['ملاءمة بين الخدمة والجمهور', 'شروط شراكة متفق عليها', 'توصية واضحة للمتابعين'],
      cta: 'تواصل بشأن الشراكة',
    },
    en: {
      eyebrow: 'Partners & referrals',
      title: 'A recommendation your audience understands.',
      description: 'Explore a Linkaza referral partnership. Discuss audience fit, commission terms, attribution and payment requirements with the team before getting started.',
      intro: 'If your audience is looking for backlink and publishing opportunities, let’s discuss a partnership with a clear purpose.',
      sections: [
        { title: 'Tell us about your audience', body: 'Share your website or channel, the content you create and the markets you reach. This helps establish whether a partnership fits and how to introduce Linkaza usefully.' },
        { title: 'Agree on the details first', body: 'Discuss commission rates, eligible orders, attribution and payment terms with the team. Partnership conditions are defined during the application process; do not assume a rate or entitlement before agreement.' },
        { title: 'Keep the recommendation transparent', body: 'Describe the service accurately and disclose your commercial relationship to your audience. Use useful examples and avoid promising search rankings or outcomes that cannot be guaranteed.' },
      ],
      bullets: ['A relevant audience', 'Agreed partnership terms', 'A transparent recommendation'],
      cta: 'Discuss a partnership',
    },
  },
  support: {
    ar: {
      eyebrow: 'مركز المساعدة',
      title: 'لنصل إلى إجابة واضحة.',
      description: 'تواصل مع دعم Linkaza للمساعدة بشأن حسابك وطلبات النشر وشروط العروض. اعرف التفاصيل التي تسرّع فهم استفسارك ومراجعته.',
      intro: 'سؤال عن عرض، أو خطوة في طلب، أو مشكلة في حسابك؟ أرسل التفاصيل إلى support@linkaza.com.',
      sections: [
        { title: 'قبل إنشاء الطلب', body: 'أرسل رابط العرض وما تريد التأكد منه: متطلبات المقال، نوع الرابط، مدة التنفيذ أو ما يشمله السعر. وضوح السؤال يساعدنا على توجيهك للمعلومة المناسبة.' },
        { title: 'بخصوص طلب قائم', body: 'اذكر رقم الطلب والبريد المرتبط بالحساب ووصفاً مختصراً للمشكلة. أضف رابط المقال إن كان منشوراً، والفرق بين ما اتُّفق عليه وما ظهر فعلياً.' },
        { title: 'خصوصية حسابك أولاً', body: 'لا ترسل كلمة المرور أو معلومات الدفع الكاملة. للاستفسارات المتعلقة بالبيانات الشخصية أو النصوص القانونية يمكنك التواصل مباشرة عبر legal@linkaza.com.' },
      ],
      bullets: ['رقم الطلب عند توفره', 'وصف واضح لما تحتاجه', 'روابط أو تفاصيل تساعد على المراجعة'],
      cta: 'راسل فريق الدعم',
    },
    en: {
      eyebrow: 'Help & support',
      title: 'Let’s get you a clear answer.',
      description: 'Contact Linkaza support about your account, placement orders or publisher terms. Find the details to include so the team can understand your question.',
      intro: 'A question about an offer, an order step or your account? Send the details to support@linkaza.com.',
      sections: [
        { title: 'Before placing an order', body: 'Include the offer URL and what you want to clarify: article requirements, link attributes, delivery timeline or what the price covers. A specific question makes it easier to find the right information.' },
        { title: 'For an existing order', body: 'Provide the order reference, your account email and a short description of the issue. If the article is live, include its URL and explain any difference from the agreed requirements.' },
        { title: 'Keep account details private', body: 'Do not send passwords or full payment details. For personal data requests or questions about the legal documents, contact legal@linkaza.com directly.' },
      ],
      bullets: ['An order reference if available', 'A clear description of the issue', 'Relevant URLs or supporting details'],
      cta: 'Email support',
    },
  },
  contact: {
    ar: {
      eyebrow: 'تواصل معنا',
      title: 'فرصتك التالية تبدأ بمحادثة.',
      description: 'تواصل مع فريق Linkaza بشأن الباك لينك والجيست بوست وخدمات المحتوى والانضمام كناشر. أرسل متطلباتك إلى support@linkaza.com.',
      intro: 'أخبرنا بما تعمل عليه، وساعدنا على فهم الجمهور والسوق والهدف الذي تريد الوصول إليه.',
      sections: [
        { title: 'للحملات وخدمات المحتوى', body: 'شارك رابط موقعك ولغة الحملة والسوق المستهدف والميزانية التقريبية. أضف الصفحات التي تريد الترويج لها وأي شروط مهمة لعلامتك.' },
        { title: 'للناشرين والشركاء', body: 'أرسل رابط موقعك أو قناتك وتخصصها ولغة محتواها. وضّح إن كنت ترغب في عرض فرص نشر أو مناقشة شراكة إحالة.' },
        { title: 'للدعم والاستفسارات', body: 'راسل support@linkaza.com للاستفسارات العامة والطلبات. وللشروط والخصوصية وطلبات البيانات الشخصية، استخدم legal@linkaza.com.' },
      ],
      bullets: ['رابط الموقع أو المشروع', 'السوق واللغة المستهدفان', 'ملخص واضح لما تحتاجه'],
      cta: 'ابدأ المحادثة',
    },
    en: {
      eyebrow: 'Contact Linkaza',
      title: 'Your next opportunity starts here.',
      description: 'Contact Linkaza about backlinks, guest posts, content requirements or becoming a publisher. Send your project details to support@linkaza.com.',
      intro: 'Tell us what you are working on, the audience you want to reach and the outcome you have in mind.',
      sections: [
        { title: 'Campaigns and content', body: 'Share your website, campaign language, target market and approximate budget. Add your priority destination pages and any important brand requirements.' },
        { title: 'Publishers and partners', body: 'Send your website or channel, subject focus and content language. Let us know whether you want to offer publishing opportunities or discuss a referral partnership.' },
        { title: 'Support and other questions', body: 'Email support@linkaza.com for general enquiries and order questions. For terms, privacy or personal data requests, use legal@linkaza.com.' },
      ],
      bullets: ['Your website or project', 'Your target language and market', 'A short description of your needs'],
      cta: 'Start a conversation',
    },
  },
  'how-it-works': {
    ar: {
      eyebrow: 'كيف تعمل Linkaza',
      title: 'من الفكرة إلى المقال المنشور.',
      description: 'تعرّف على خطوات شراء باك لينك أو جيست بوست عبر Linkaza: اختيار الموقع، مراجعة العرض، إرسال المحتوى والتحقق من النشر.',
      intro: 'مسار واضح يساعدك على تحويل هدف حملتك إلى طلب نشر بتفاصيل معروفة.',
      sections: [
        { title: 'اختر الموقع وراجع العرض', body: 'ابدأ بحسابك في المنصة، ثم ابحث عن موقع يناسب موضوعك وجمهورك. راجع السعر ومتطلبات المحتوى ونوع الرابط والمدة المتوقعة وشروط بقاء النشر.' },
        { title: 'جهّز الطلب والمحتوى', body: 'حدّد الصفحة المستهدفة والنص الرابط وأرفق المقال أو متطلبات الكتابة إذا كانت متاحة ضمن العرض. تأكد من التفاصيل وطريقة الدفع قبل إرسال الطلب.' },
        { title: 'راجع المقال عند النشر', body: 'بعد قبول الناشر وتنفيذ الطلب، افتح رابط المقال وتحقق من المحتوى والرابط وفق الاتفاق. احتفظ بمرجع الطلب وتواصل مع الدعم عند وجود اختلاف يحتاج مراجعة.' },
      ],
      bullets: ['اختر موقعاً مناسباً', 'اعتمد تفاصيل الطلب', 'راجع ما تم نشره'],
      cta: 'ابدأ طلبك الأول',
    },
    en: {
      eyebrow: 'How Linkaza works',
      title: 'From an idea to a published article.',
      description: 'See how to order a backlink or guest post through Linkaza: choose a publisher, review the offer, prepare your content and check the published placement.',
      intro: 'A clear path from your campaign goal to a publishing order with defined requirements.',
      sections: [
        { title: 'Choose a publisher and review the offer', body: 'Start in your platform account and find a website that fits your subject and audience. Review pricing, content requirements, link attributes, the expected timeline and publication duration.' },
        { title: 'Prepare the order and content', body: 'Specify your destination page and anchor text. Provide the article or a writing brief where that service is available. Confirm the requirements and payment method before submitting.' },
        { title: 'Review the live placement', body: 'Once the publisher accepts and completes the order, open the article and check the content and link against the agreement. Keep the order reference and contact support about any discrepancy.' },
      ],
      bullets: ['Choose a relevant website', 'Confirm the order requirements', 'Review the published result'],
      cta: 'Start your first order',
    },
  },
  'guest-posts': {
    ar: {
      eyebrow: 'الجيست بوست',
      title: 'خبرتك، أمام جمهور جديد.',
      description: 'اكتشف فرص جيست بوست عربية وإنكليزية مع Linkaza. اختر مواقع تناسب تخصصك وانشر محتوى مفيداً يعرّف القرّاء بخبرتك وعلامتك.',
      intro: 'المقال الجيد يضيف للموقع الذي ينشره، ويمنح علامتك حضوراً في سياق يهم القارئ.',
      sections: [
        { title: 'ما هو الجيست بوست؟', body: 'الجيست بوست مقال يقدّمه كاتب أو علامة للنشر على موقع آخر. تختلف شروطه بين الناشرين؛ وقد يتضمن رابطاً ذا صلة إلى موقعك ضمن المحتوى أو التعريف بالكاتب بحسب الاتفاق.' },
        { title: 'اختر زاوية تخصّ هذا الجمهور', body: 'اقرأ مقالات الموقع قبل إعداد الموجز. اقترح موضوعاً يكمّل تغطيته، مع تجربة أو مثال أو تحليل أصلي. المقال المصمم لموقع بعينه أكثر ملاءمة من نص عام يُرسل إلى الجميع.' },
        { title: 'اتفق على تفاصيل النشر', body: 'راجع قواعد التحرير ونوع الرابط وظهور المقال ومدته وحقوق استخدام المحتوى. عندما يكون النشر مدفوعاً، يجب توضيح العلاقة واستخدام وسم sponsored أو nofollow وفق إرشادات Google.' },
      ],
      bullets: ['موضوع مرتبط بتخصص الناشر', 'محتوى أصلي وله غرض', 'شروط تحرير وروابط واضحة'],
      cta: 'اكتشف فرص الجيست بوست',
    },
    en: {
      eyebrow: 'Guest posting',
      title: 'Your expertise. A new audience.',
      description: 'Explore Arabic and English guest post opportunities with Linkaza. Choose relevant publishers and create useful articles that introduce readers to your expertise.',
      intro: 'A good guest article contributes to its host publication and gives readers a relevant reason to discover your brand.',
      sections: [
        { title: 'What is a guest post?', body: 'A guest post is an article contributed by an outside author or brand to another publication. Publisher requirements vary; a relevant link may appear in the content or author information, depending on the agreement.' },
        { title: 'Choose an angle for this readership', body: 'Read the publication before preparing your brief. Propose a topic that complements its coverage, with an original example, experience or analysis. An article written for a particular audience is more useful than a generic draft sent everywhere.' },
        { title: 'Agree on the publishing details', body: 'Review editorial rules, link attributes, article visibility, duration and content rights. Paid placements should disclose the relationship and use sponsored or nofollow link attributes in line with Google’s guidance.' },
      ],
      bullets: ['A topic relevant to the publisher', 'Original content with a purpose', 'Clear editorial and link requirements'],
      cta: 'Find guest post opportunities',
    },
  },
  'quality-standards': {
    ar: {
      eyebrow: 'اختيار الجودة',
      title: 'جودة الباك لينك ليست رقماً واحداً.',
      description: 'تعرّف على معايير تقييم مواقع الباك لينك والجيست بوست: الصلة بالموضوع والجمهور والزيارات وجودة التحرير وشروط النشر قبل الشراء.',
      intro: 'هذه المعايير تساعدك على تقييم العرض. وتبقى بيانات كل موقع وتفاصيله هي أساس قرارك.',
      sections: [
        { title: 'صلة يمكن تفسيرها', body: 'هل يتناول الموقع موضوعات قريبة من نشاطك؟ وهل يضيف المقال المقترح شيئاً لقرّائه؟ افحص اللغة والجمهور وأمثلة النشر، ولا تكتفِ بتطابق كلمة في اسم التصنيف.' },
        { title: 'بيانات تقرؤها في سياقها', body: 'راجع مصدر الزيارات واتجاهها والدول والصفحات المهمة. اسأل عن مصدر الأرقام وتاريخها، وميّز بين القياسات المباشرة والتقديرات. لا يعني ارتفاع DA أو DR أن كل فرصة في الموقع مناسبة.' },
        { title: 'تحرير وشروط واضحة', body: 'افحص جودة المقالات وتنوعها وظهور المحتوى في أقسام الموقع. قبل الطلب، تأكد من خصائص الرابط ومتطلبات المراجعة ومدة النشر وما يحدث إذا خالف التسليم الشروط المتفق عليها.' },
      ],
      bullets: ['التخصص والجمهور', 'مصدر البيانات وحداثتها', 'جودة المحتوى ووضوح العرض'],
      cta: 'قارن فرص النشر',
    },
    en: {
      eyebrow: 'Evaluating quality',
      title: 'Backlink quality is more than one score.',
      description: 'Evaluate backlink and guest post publishers through relevance, audience, traffic evidence, editorial quality and clear placement terms before purchasing.',
      intro: 'Use these criteria to assess an offer. The specific publisher’s evidence and terms remain the basis for your decision.',
      sections: [
        { title: 'Relevance you can explain', body: 'Does the website cover subjects close to your business? Would the proposed article help its readers? Review language, audience and published examples instead of relying on a matching category label.' },
        { title: 'Data in its proper context', body: 'Review traffic sources, trends, audience countries and important pages. Ask where figures come from and when they were updated. Distinguish direct measurements from estimates; a higher DA or DR does not make every placement a good fit.' },
        { title: 'Editorial quality and clear terms', body: 'Read recent articles and check how content is linked from the publication’s sections. Before ordering, confirm link attributes, revision requirements, placement duration and the process if delivery differs from the agreement.' },
      ],
      bullets: ['Subject and audience relevance', 'Data sources and freshness', 'Editorial quality and clear terms'],
      cta: 'Compare publishing opportunities',
    },
  },
  faq: {
    ar: {
      eyebrow: 'الأسئلة الشائعة',
      title: 'تفاصيل تستحق أن تعرفها.',
      description: 'إجابات عن Linkaza والباك لينك والجيست بوست: اختيار الموقع، الأسعار، المحتوى، مدد النشر والفرق بين تنفيذ الطلب ونتائج محركات البحث.',
      intro: 'افهم طريقة العمل وما تحتاج إلى مراجعته قبل اختيار أول عرض.',
      sections: [
        { title: 'هل تشمل الأسعار كتابة المقال؟', body: 'يعتمد ذلك على العرض. بعض فرص النشر تتطلب مقالاً جاهزاً، وقد تتوفر الكتابة كخدمة اختيارية. راجع تفاصيل الناشر وتكلفة المحتوى قبل اعتماد الطلب.' },
        { title: 'كم يستغرق النشر؟ وما مدة بقاء الرابط؟', body: 'تختلف مدة التنفيذ ومدة بقاء النشر بحسب الناشر والعرض. راجعهما قبل الشراء ولا تفترض مدة موحّدة. عند وجود مشكلة، يعتمد تقييمها على شروط الطلب وما تم تسليمه.' },
        { title: 'هل تضمن Linkaza ترتيباً في Google؟', body: 'لا. ترتيب البحث يتأثر بعوامل متعددة ولا تضمن Linkaza مركزاً محدداً أو زيادة في الزيارات. وعند شراء النشر المدفوع، راجع الإفصاح وخصائص الرابط المناسبة ضمن شروط العرض.' },
      ],
      bullets: ['الناشر يحدّد سعر العرض', 'شروط كل طلب تُراجع قبل الشراء', 'الدعم متاح لاستفساراتك'],
      cta: 'لديك سؤال آخر؟ تواصل معنا',
    },
    en: {
      eyebrow: 'Frequently asked questions',
      title: 'The details worth knowing.',
      description: 'Answers about Linkaza backlinks and guest posts: publisher selection, pricing, content, publication periods and what search results cannot be guaranteed.',
      intro: 'Understand the process and the details to review before choosing your first offer.',
      sections: [
        { title: 'Does the price include an article?', body: 'It depends on the offer. Some placements require a ready-to-publish article; writing may be available as an optional service. Review the publisher requirements and content costs before confirming your order.' },
        { title: 'How long does publication take, and how long does it stay live?', body: 'Delivery time and publication duration vary by publisher and offer. Check both before buying rather than assuming a standard period. Any delivery issue is assessed against the agreed order terms.' },
        { title: 'Does Linkaza guarantee Google rankings?', body: 'No. Search performance depends on many factors, and Linkaza does not guarantee a position or traffic increase. For paid placements, review the disclosure and appropriate link attributes as part of the offer.' },
      ],
      bullets: ['Publishers set placement prices', 'Review each order’s terms before buying', 'Contact support for specific questions'],
      cta: 'Ask us another question',
    },
  },
  terms: {
    ar: {
      eyebrow: 'آخر تحديث: 23 أكتوبر 2025',
      title: 'الشروط والأحكام',
      description: 'الشروط التي تحكم استخدام موقع Linkaza ومنصته وخدماته، بما في ذلك الحسابات والطلبات والمدفوعات والتزامات المشترين والناشرين.',
      intro: 'تحكم هذه الشروط وصولك إلى موقع Linkaza ومنصته وخدماته، المملوكة والمشغّلة من قِبل Linkaza. باستخدام الخدمة، فإنك توافق على الالتزام بهذه الشروط. إذا كنت لا توافق عليها، فلا يجوز لك استخدام الخدمة.',
      sections: [
        { title: '1. التعريفات', body: '«الخدمة» تعني منصة Linkaza وموقعها وجميع الخدمات المرتبطة بها. «المستخدم» يعني أي فرد أو جهة تنشئ حساباً وتستخدم الخدمة، ويشمل المشترين والناشرين. «مكان النشر» يعني نشر محتوى يتضمن باك لينك على موقع ناشر. «المحتوى» يشمل المقالات والنصوص والصور والمواد المقدّمة أو المنشأة فيما يتصل بالنشر.' },
        { title: '2. تسجيل الحساب واستخدامه', body: 'يتطلب استخدام الخدمة التسجيل بمعلومات دقيقة وحديثة وكاملة. أنت مسؤول عن حماية كلمة مرورك وعن الأنشطة التي تتم عبر حسابك، وعليك إخطارنا فور علمك بخرق أمني أو استخدام غير مصرّح به. يجب أن يكون عمرك 18 عاماً على الأقل لاستخدام الخدمة.' },
        { title: '3. الخدمة', body: 'تقدّم Linkaza سوقاً يربط المشترين الباحثين عن باك لينك بالناشرين الراغبين في بيع فرص نشر على مواقعهم. قد تتوفر خدمة كتابة محتوى اختيارية لتسهيل النشر. نحتفظ بحق رفض تقديم الخدمة لأي شخص لأي سبب وفي أي وقت.' },
        { title: '4. المدفوعات والأرصدة والاسترداد', body: 'تعمل الخدمة بنظام الدفع بحسب الاستخدام، من خلال رصيد الحساب أو الدفع لكل طلب. يحدّد الناشرون أسعار النشر وتُعرض في السوق. تُدرس طلبات الاسترداد حالةً بحالة؛ وقد يُقبل الاسترداد عند عدم تنفيذ النشر أو عدم مطابقته للمتطلبات المتفق عليها أو إزالة الرابط خلال فترة الضمان المحددة في العرض، مثل 12 شهراً إذا نُص عليها. لا يُرد مقابل الروابط التي سُلّمت وفق الطلب وما تزال منشورة.' },
        { title: '5. التزامات المشترين والناشرين', body: 'يلتزم المشتري بتقديم بيانات طلب دقيقة، بما فيها الصفحة المستهدفة والنص الرابط، ويقر بأن قرار النشر النهائي يعود إلى الناشر وأن Linkaza لا تضمن ترتيباً أو نتائج سيو محددة أو زيادة في الزيارات. ويلتزم الناشر بتمثيل بيانات موقعه وشروطه بدقة، ونشر المحتوى المعتمد في الوقت المناسب، والإبقاء على الرابط طوال الحد الأدنى للضمان المحدد في عرضه.' },
        { title: '6. القانون الحاكم', body: 'تخضع هذه الشروط وتُفسّر وفقاً لقوانين المملكة المتحدة، دون اعتبار لأحكام تنازع القوانين.' },
        { title: '7. التواصل', body: 'للاستفسارات المتعلقة بهذه الشروط، راسل legal@linkaza.com.' },
      ],
      bullets: ['شروط العرض تحدّد تفاصيل الطلب', 'لا ضمان لنتائج البحث', 'للاستفسارات: legal@linkaza.com'],
      cta: 'تواصل بشأن الشروط',
    },
    en: {
      eyebrow: 'Last updated: October 23, 2025',
      title: 'Terms and conditions',
      description: 'Terms governing the Linkaza website, platform and services, including accounts, placement orders, payments and buyer and publisher obligations.',
      intro: 'These terms govern access to the Linkaza website, platform and related services, owned and operated by Linkaza. By accessing or using the service, you agree to these terms. If you disagree with any part, you may not use the service.',
      sections: [
        { title: '1. Definitions', body: '“Service” means the Linkaza platform, website and related services. “User” means an individual or entity that creates an account and uses the service, including buyers and publishers. “Placement” means publication of content containing a backlink on a publisher’s website. “Content” includes articles, text, images and other materials provided or created in connection with a placement.' },
        { title: '2. Account registration and use', body: 'To use the service, you must register with accurate, current and complete information. You are responsible for safeguarding your password and for activity under your account. Notify us immediately when you become aware of a security breach or unauthorized account use. You must be at least 18 years old to use the service.' },
        { title: '3. The service', body: 'Linkaza provides a marketplace connecting buyers seeking backlinks with publishers offering placements on their websites. An optional content writing service may also be provided to facilitate placements. We reserve the right to refuse service to anyone for any reason at any time.' },
        { title: '4. Payments, credits and refunds', body: 'The service operates on a pay-as-you-go basis through an account wallet or payment per order. Publishers set placement prices, which are displayed in the marketplace. Refunds are considered case by case, including non-delivery, failure to meet agreed requirements, or removal during a specified guarantee period, such as 12 months where included in the offer. No refunds are issued for links delivered as ordered that remain live.' },
        { title: '5. Buyer and publisher obligations', body: 'Buyers must supply accurate order information, including target URLs and anchor text. Buyers acknowledge that publishers make the final publication decision and that Linkaza does not guarantee specific SEO results, rankings or traffic increases. Publishers must accurately represent their website metrics and guidelines, publish approved content in a timely manner and maintain the link for the minimum guarantee period specified in their listing.' },
        { title: '6. Governing law', body: 'These terms are governed and construed in accordance with the laws of the United Kingdom, without regard to conflict of law provisions.' },
        { title: '7. Contact', body: 'For questions about these terms, contact legal@linkaza.com.' },
      ],
      bullets: ['The offer defines order-specific terms', 'Search outcomes are not guaranteed', 'Questions: legal@linkaza.com'],
      cta: 'Contact us about these terms',
    },
  },
  'privacy-policy': {
    ar: {
      eyebrow: 'آخر تحديث: 23 أكتوبر 2025',
      title: 'سياسة الخصوصية وملفات الارتباط',
      description: 'تعرّف على طريقة جمع Linkaza للمعلومات واستخدامها ومشاركتها وحمايتها، وملفات تعريف الارتباط وحقوق البيانات ووسيلة التواصل.',
      intro: 'توضّح هذه السياسة كيفية جمع Linkaza للمعلومات واستخدامها والإفصاح عنها وحمايتها عند زيارة الموقع أو استخدام المنصة والخدمات. يُرجى قراءتها بعناية؛ باستخدام الخدمة، فإنك توافق على ممارسات البيانات الموضحة هنا.',
      sections: [
        { title: '1. المعلومات التي نجمعها', body: 'قد نجمع معلومات شخصية مثل الاسم والبريد الإلكتروني واسم الشركة ومعلومات الدفع، ومعلومات تجمعها الخوادم تلقائياً مثل عنوان IP ونوع المتصفح ونظام التشغيل. نحتفظ بمعلومات مالية محدودة جداً، بينما تُخزّن بقية المعلومات المالية لدى معالج الدفع.' },
        { title: '2. كيف نستخدم المعلومات', body: 'قد نستخدم المعلومات لإنشاء حسابك وإدارته، ومعالجة المعاملات وتقديم الخدمات المطلوبة، والتواصل بشأن الحساب أو الطلبات، وتحليل الاستخدام لتحسين التجربة، ومنع المعاملات الاحتيالية ومراقبة السرقة.' },
        { title: '3. مشاركة المعلومات', body: 'لا نبيع أو نتاجر أو نؤجّر معلوماتك التعريفية الشخصية. قد نشارك المعلومات للاستجابة لإجراءات قانونية عندما نعتقد أن الإفصاح ضروري، أو مع مزوّدي خدمات يعملون نيابة عنا، مثل مزوّدي معالجة الدفع والاستضافة.' },
        { title: '4. ملفات تعريف الارتباط', body: 'قد تستخدم الخدمة ملفات تعريف الارتباط وإشارات الويب وبكسلات التتبّع وتقنيات مشابهة لتخصيص التجربة وتحسينها. يمكنك إزالة ملفات الارتباط أو رفضها عبر إعدادات المتصفح، لكن ذلك قد يؤثر في توفر بعض وظائف الخدمة.' },
        { title: '5. أمان البيانات', body: 'نستخدم إجراءات إدارية وتقنية ومادية للمساعدة على حماية المعلومات الشخصية. مع اتخاذ خطوات معقولة للحماية، لا توجد إجراءات أمان كاملة أو منيعة تماماً.' },
        { title: '6. حقوق حماية البيانات', body: 'بحسب موقعك والقوانين المطبقة، قد يحق لك الوصول إلى بياناتك الشخصية وطلب نسخة منها، وتصحيح المعلومات غير الدقيقة، وطلب محو البيانات أو تقييد معالجتها.' },
        { title: '7. تحديثات هذه السياسة', body: 'قد نحدّث السياسة من وقت لآخر. تُنشر التغييرات على هذه الصفحة مع تحديث تاريخ آخر مراجعة.' },
        { title: '8. التواصل', body: 'للأسئلة أو الملاحظات أو طلبات الخصوصية، راسل legal@linkaza.com.' },
      ],
      bullets: ['معلومات الحساب والطلبات', 'حقوق تختلف حسب القانون المطبق', 'للتواصل: legal@linkaza.com'],
      cta: 'تواصل بشأن الخصوصية',
    },
    en: {
      eyebrow: 'Last updated: October 23, 2025',
      title: 'Privacy & cookie policy',
      description: 'Learn how Linkaza collects, uses, shares and protects information, and read about cookies, data protection rights and privacy contact details.',
      intro: 'This policy explains how Linkaza collects, uses, discloses and safeguards information when you visit our website or use the platform and services. Please read it carefully. By using the service, you consent to the data practices described here.',
      sections: [
        { title: '1. Information we collect', body: 'We may collect personal information such as your name, email, company name and payment information, as well as server-collected details such as IP address, browser type and operating system. We store very limited financial information; other financial information is stored by our payment processor.' },
        { title: '2. How we use information', body: 'We may use information to create and manage your account, process transactions and deliver requested services, contact you about accounts or orders, analyze usage to improve the experience, and prevent fraudulent transactions and monitor against theft.' },
        { title: '3. Sharing information', body: 'We do not sell, trade or rent personally identifiable information. Information may be shared where we believe disclosure is necessary to respond to legal process, or with service providers working on our behalf, such as payment processors and hosting providers.' },
        { title: '4. Cookies', body: 'The service may use cookies, web beacons, tracking pixels and similar technologies to customize and improve the experience. You can remove or reject cookies through browser settings, but this may affect the availability and functionality of parts of the service.' },
        { title: '5. Data security', body: 'We use administrative, technical and physical measures to help protect personal information. Although we take reasonable steps to secure information, no security measures are perfect or impenetrable.' },
        { title: '6. Data protection rights', body: 'Depending on your location and applicable law, you may have rights to access and obtain copies of personal data, correct inaccurate information, request erasure or restrict processing.' },
        { title: '7. Policy updates', body: 'We may update this policy from time to time. Changes will be posted on this page with an updated last-reviewed date.' },
        { title: '8. Contact', body: 'For privacy questions, comments or requests, contact legal@linkaza.com.' },
      ],
      bullets: ['Account and order information', 'Rights depend on applicable law', 'Contact: legal@linkaza.com'],
      cta: 'Contact us about privacy',
    },
  },
};
