'use client';
import { useState } from 'react';
import Link from 'next/link';
import { choose, hrefFor, type Locale } from '@/lib/site';
import { Icon } from './icon';

const audiences = [
  { slug: 'agencies', icon: 'layers', ar: 'للوكالات', en: 'For agencies', title: { ar: 'معايير واضحة لكل عميل.', en: 'Clear criteria for each client.' }, body: { ar: 'اختَر فرص النشر المناسبة لكل مشروع. قارن المواقع، وحافظ على وضوح المتطلبات والتكلفة قبل اعتماد كل طلب.', en: 'Find relevant publishing opportunities for each project. Compare websites and keep requirements and costs clear before approving an order.' }, points: { ar: ['مقارنة المواقع قبل الطلب', 'متطلبات واضحة لكل مشروع', 'متابعة الطلبات من حسابك'], en: ['Compare websites before ordering', 'Clear requirements for each project', 'Follow orders in your account'] } },
  { slug: 'businesses', icon: 'chart', ar: 'للشركات', en: 'For businesses', title: { ar: 'وصل علامتك بالجمهور المناسب.', en: 'Put your brand in the right company.' }, body: { ar: 'ابدأ من جمهورك، لا من عدد الروابط. ابحث عن ناشرين في مجال عملك وقدّم محتوى يضيف قيمة لقارئه ويشرح ما يميّز علامتك.', en: 'Start with your audience, not a link count. Explore publishers in your industry and share content that gives readers a reason to care about your brand.' }, points: { ar: ['اختيار حسب المجال واللغة', 'ميزانية تناسب كل مرحلة', 'محتوى يحمل صوت علامتك'], en: ['Choose by topic and language', 'A budget for your current stage', 'Content with your brand’s voice'] } },
  { slug: 'publishers', icon: 'document', ar: 'للناشرين', en: 'For publishers', title: { ar: 'اعرض موقعك بشروط واضحة.', en: 'List your website with clear terms.' }, body: { ar: 'عرّف المعلنين بموقعك وجمهوره، وحدّد أسعارك وقواعدك التحريرية. استقبل الطلبات التي تناسب طبيعة المحتوى الذي تقدّمه.', en: 'Introduce your website and audience to advertisers. Set your prices and editorial requirements, and review orders that fit your publication.' }, points: { ar: ['عرض موقعك وتخصصه', 'شروط نشر تحددها أنت', 'قرار تحريري يبقى بيدك'], en: ['Showcase your publication', 'Publishing terms set by you', 'Keep your editorial control'] } },
];
export function AudienceTabs({ locale }: { locale: Locale }) {
  const [selected, setSelected] = useState(0);
  const item = audiences[selected];
  return <div className="audience-layout">
    <div className="audience-visual" aria-hidden="true"><div className="project-window"><div className="window-dots"><i/><i/><i/></div><div className="project-title"><span className="project-avatar"><Icon name={item.icon}/></span><div><strong>{choose(locale, 'مساحة مشروعك', 'Your project space')}</strong><span>{choose(locale, 'تنظيم أوضح. قرارات أفضل.', 'More clarity. Better decisions.')}</span></div></div>{[0,1,2].map((x) => <div className="project-row" key={x}><span className={`mini-icon mini-${x}`}><Icon name={['document','globe','check'][x]}/></span><div><span style={{width: `${80-x*12}%`}}/><span style={{width:`${55+x*5}%`}}/></div><span className="mini-status"><Icon name="check"/></span></div>)}<div className="window-footer">{choose(locale, 'تصوّر توضيحي لتجربة المنصة', 'Illustration of the platform experience')}<Icon name="layers"/></div></div><div className="floating-tag"><Icon name="check"/>{choose(locale, 'كل التفاصيل في مكان واحد', 'All the details. One place.')}</div><span className="visual-orbit"/></div>
    <div className="audience-copy"><div className="eyebrow">{choose(locale, 'حلول حسب طريقة عملك', 'BUILT AROUND YOUR WORK')}</div><h2>{choose(locale, 'اختر المسار المناسب لك.', 'Choose the path that fits your work.')}</h2><div className="audience-buttons" aria-label={choose(locale, 'اختر نوع مشروعك', 'Choose your business type')}>{audiences.map((audience, index) => <button key={audience.slug} aria-pressed={selected === index} onClick={() => setSelected(index)}>{audience[locale]}</button>)}</div><div className="audience-panel" aria-live="polite"><h3>{item.title[locale]}</h3><p>{item.body[locale]}</p><ul className="check-list">{item.points[locale].map(point => <li key={point}><Icon name="check"/>{point}</li>)}</ul><Link className="text-link" href={hrefFor(locale,item.slug)} prefetch={false}>{choose(locale, 'اكتشف الحل المناسب لك', 'Find your solution')}<Icon name="arrow"/></Link></div></div>
  </div>;
}
