import Link from 'next/link';
import { articles } from '@/lib/articles';
import { choose, faqs, hrefFor, type Locale } from '@/lib/site';
import { Icon } from './icon';

export function FaqSection({ locale }: { locale: Locale }) {
  return <section className="section container faq-section"><div className="faq-intro"><span className="eyebrow">{choose(locale,'أجوبة واضحة','A LITTLE MORE CLARITY')}</span><h2>{choose(locale,'قبل أن تبدأ،\nقد تتساءل…','Before you start,\nyou might wonder…')}</h2><p>{choose(locale,'قرار أفضل يبدأ بمعلومات أوضح. وإذا بقي لديك سؤال، نحن هنا للمساعدة.','Better decisions start with better information. Have another question? We’re here to help.')}</p><Link className="text-link" href={hrefFor(locale,'contact')} prefetch={false}>{choose(locale,'اسأل فريقنا','Talk to our team')}<Icon name="arrow"/></Link></div><div className="faq-list">{faqs[locale].map(([question,answer],index) => <details key={question}><summary><span className="faq-number">0{index+1}</span><span>{question}</span><Icon name="plus"/></summary><p>{answer}</p></details>)}</div></section>;
}

export function Resources({ locale, full = false }: { locale: Locale; full?: boolean }) {
  return <section className={`section container resources-section ${full ? 'resources-full' : ''}`}><div className="section-heading"><div><span className="eyebrow">{choose(locale,'المعرفة قبل القرار','KNOW MORE. CHOOSE BETTER.')}</span><h2>{choose(locale,'خطوتك الأذكى تبدأ بفكرة.','A smarter next step starts here.')}</h2></div>{!full && <Link className="text-link" href={hrefFor(locale,'blog')} prefetch={false}>{choose(locale,'مركز المعرفة','All resources')}<Icon name="arrow"/></Link>}</div><div className="resource-grid">{articles.map((article,index) => <article className="resource-card" key={article.slug}><Link href={hrefFor(locale,`blog/${article.slug}`)} className="resource-visual" tabIndex={-1} aria-hidden="true" prefetch={false}><div className={`editorial-art editorial-art-${index}`}><div className="art-grid"/>{index === 0 ? <><div className="art-score"><Icon name="shield"/><span>QUALITY<br/>OVER QUANTITY</span></div><span className="art-circle"/></> : index === 1 ? <><div className="art-paper"><i/><i/><i/><span><Icon name="link"/></span></div><div className="art-paper paper-back"/><span className="art-orbit"/></> : <><div className="art-bars">{[25,45,38,68,87].map((height,i) => <i style={{height:`${height}%`}} key={i}/>)}</div><span className="art-chip">SMARTER<br/>SPENDING ↗</span></>}<span className="art-index">0{index+1} — LINKAZA JOURNAL</span></div></Link><div className="resource-meta"><span>{article.category[locale]}</span><span>{article.readTime} {choose(locale,'دقائق قراءة','min read')}</span></div><h3><Link href={hrefFor(locale,`blog/${article.slug}`)} prefetch={false}>{article.title[locale]}</Link></h3><p>{article.description[locale]}</p><Link className="text-link" href={hrefFor(locale,`blog/${article.slug}`)} prefetch={false}>{choose(locale,'اقرأ الدليل','Read the guide')}<Icon name="arrow"/></Link></article>)}</div></section>;
}
