import Link from 'next/link';
import { choose, hrefFor, type Locale } from '@/lib/site';
import { AuthLink } from './auth-link';
import { BrandMark, Icon } from './icon';

export function ClosingCta({ locale }: { locale: Locale }) {
  return <section className="closing-section container"><div className="closing-cta"><div className="closing-art" aria-hidden="true"><i/><i/><i/><Icon name="link"/></div><div className="closing-copy"><span className="eyebrow">{choose(locale, 'خطوتك التالية تبدأ هنا', 'YOUR NEXT CHAPTER STARTS HERE')}</span><h2>{choose(locale, 'دع قصّتك تصل أبعد.', 'Let your story travel further.')}</h2><p>{choose(locale, 'المحتوى المناسب يستحق المكان المناسب. اكتشف فرصتك القادمة مع لينكازا.', 'Great content deserves the right audience. Discover your next opportunity with Linkaza.')}</p><AuthLink locale={locale} destination="register" className="button button-lime">{choose(locale, 'أنشئ حسابك الآن', 'Create your account')}<Icon name="up"/></AuthLink><span className="cta-footnote">{choose(locale, 'راجع المواقع وشروط العروض قبل الطلب', 'Review publishers and offer terms before ordering')}</span></div></div></section>;
}

export function SiteFooter({ locale }: { locale: Locale }) {
  const groups = [
    { title: choose(locale,'المنصة','Platform'), links: [['marketplace','سوق المواقع','Marketplace'],['guest-posts','الجيست بوست','Guest posts'],['pricing','الأسعار','Pricing'],['how-it-works','كيف تعمل','How it works'],['content-service','خدمات المحتوى','Content services'],['strategy-builder','بناء الاستراتيجية','Campaign planning']] },
    { title: choose(locale,'لأجلك','Made for you'), links: [['agencies','الوكالات','Agencies'],['businesses','الشركات','Businesses'],['consultants','خبراء السيو','SEO consultants'],['publishers','الناشرون','Publishers'],['analytics','قياس الأداء','Measurement'],['affiliate','الشراكات والإحالات','Partnerships']] },
    { title: choose(locale,'اكتشف أكثر','Explore more'), links: [['about','عن لينكازا','About Linkaza'],['blog','مركز المعرفة','Resources'],['quality-standards','معايير الجودة','Quality standards'],['faq','الأسئلة الشائعة','FAQs'],['contact','تواصل معنا','Contact us']] },
  ];
  return <footer className="site-footer"><div className="container footer-grid"><div className="footer-about"><Link className="brand" href={hrefFor(locale)} prefetch={false}><BrandMark/><span>linkaza<span className="brand-dot">.</span></span></Link><p>{choose(locale,'نصل القصص الجيدة بالأماكن الصحيحة. منصة باك لينك وجيست بوست، تبدأ بفهم جمهورك.','Connecting good stories with the right places. A backlink and guest post marketplace that starts with your audience.')}</p><a href="mailto:support@linkaza.com" className="footer-email"><Icon name="mail"/><span dir="ltr">support@linkaza.com</span></a></div>{groups.map(group => <div className="footer-column" key={group.title}><h3>{group.title}</h3>{group.links.map(([slug,ar,en]) => <Link key={slug} href={hrefFor(locale,slug)} prefetch={false}>{choose(locale,ar,en)}</Link>)}</div>)}</div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Linkaza. {choose(locale,'جميع الحقوق محفوظة.','All rights reserved.')}</span><div><Link href={hrefFor(locale,'terms')} prefetch={false}>{choose(locale,'الشروط والأحكام','Terms of service')}</Link><Link href={hrefFor(locale,'privacy-policy')} prefetch={false}>{choose(locale,'سياسة الخصوصية','Privacy policy')}</Link><Link href={hrefFor(locale,'support')} prefetch={false}>{choose(locale,'الدعم','Support')}</Link></div><span className="footer-made"><span/>{choose(locale,'روابط مدروسة. أثر حقيقي.','Thoughtful connections.')}</span></div></footer>;
}
