import Link from 'next/link';
import { choose, hrefFor, type Locale } from '@/lib/site';
import { AuthLink } from './auth-link';
import { BrandMark, Icon } from './icon';

export function ClosingCta({ locale }: { locale: Locale }) {
  return <section className="closing-section container"><div className="closing-cta"><div className="closing-art" aria-hidden="true"><i/><i/><i/><Icon name="link"/></div><div className="closing-copy"><span className="eyebrow">{choose(locale, 'ابدأ من السوق', 'START WITH THE MARKETPLACE')}</span><h2>{choose(locale, 'اختر موقع النشر قبل أن تطلب.', 'Choose the publisher before you order.')}</h2><p>{choose(locale, 'قارن المواقع والأسعار وشروط النشر، ثم أرسل طلبك من لوحة لينكازا.', 'Compare publishers, prices and placement terms, then submit your order from the Linkaza dashboard.')}</p><AuthLink locale={locale} destination="register" className="button button-lime">{choose(locale, 'أنشئ حسابك الآن', 'Create your account')}<Icon name="up"/></AuthLink><span className="cta-footnote">{choose(locale, 'راجع المواقع وشروط العروض قبل الطلب', 'Review publishers and offer terms before ordering')}</span></div></div></section>;
}

export function SiteFooter({ locale }: { locale: Locale }) {
  const groups = [
    { title: choose(locale,'المنصة','Platform'), links: [['marketplace','سوق المواقع','Marketplace'],['guest-posts','الجيست بوست','Guest posts'],['pricing','الأسعار','Pricing'],['how-it-works','كيف تعمل','How it works'],['content-service','خدمات المحتوى','Content services'],['strategy-builder','بناء الاستراتيجية','Campaign planning']] },
    { title: choose(locale,'لأجلك','Made for you'), links: [['agencies','الوكالات','Agencies'],['businesses','الشركات','Businesses'],['consultants','خبراء السيو','SEO consultants'],['publishers','الناشرون','Publishers'],['analytics','قياس الأداء','Measurement'],['affiliate','الشراكات والإحالات','Partnerships']] },
    { title: choose(locale,'اكتشف أكثر','Explore more'), links: [['about','عن لينكازا','About Linkaza'],['blog','مركز المعرفة','Resources'],['quality-standards','معايير الجودة','Quality standards'],['faq','الأسئلة الشائعة','FAQs'],['contact','تواصل معنا','Contact us']] },
  ];
  return <footer className="site-footer"><div className="container footer-grid"><div className="footer-about"><Link className="brand" href={hrefFor(locale)} prefetch={false}><BrandMark/><span>linkaza<span className="brand-dot">.</span></span></Link><p>{choose(locale,'سوق باك لينك وجيست بوست يساعدك على مقارنة الناشرين وشروط النشر قبل الطلب.','A backlink and guest post marketplace that helps you compare publishers and placement terms before ordering.')}</p><a href="mailto:support@linkaza.com" className="footer-email"><Icon name="mail"/><span dir="ltr">support@linkaza.com</span></a></div>{groups.map(group => <div className="footer-column" key={group.title}><h3>{group.title}</h3>{group.links.map(([slug,ar,en]) => <Link key={slug} href={hrefFor(locale,slug)} prefetch={false}>{choose(locale,ar,en)}</Link>)}</div>)}</div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Linkaza. {choose(locale,'جميع الحقوق محفوظة.','All rights reserved.')}</span><div><Link href={hrefFor(locale,'terms')} prefetch={false}>{choose(locale,'الشروط والأحكام','Terms of service')}</Link><Link href={hrefFor(locale,'privacy-policy')} prefetch={false}>{choose(locale,'سياسة الخصوصية','Privacy policy')}</Link><Link href={hrefFor(locale,'support')} prefetch={false}>{choose(locale,'الدعم','Support')}</Link></div><span className="footer-made"><span/>{choose(locale,'اختيار أوضح قبل الطلب.','Clearer choices before ordering.')}</span></div></footer>;
}
